(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


// symbols:



(lib._1rearbg = function() {
	this.initialize(img._1rearbg);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,269,184);


(lib._1front = function() {
	this.initialize(img._1front);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,492,403);


(lib._1left = function() {
	this.initialize(img._1left);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,253,191);


(lib._2grass1 = function() {
	this.initialize(img._2grass1);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,458,129);


(lib._2upleft = function() {
	this.initialize(img._2upleft);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,329,266);


(lib._2front = function() {
	this.initialize(img._2front);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,460,167);


(lib._3grass2 = function() {
	this.initialize(img._3grass2);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,458,201);


(lib._3middle = function() {
	this.initialize(img._3middle);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,460,293);


(lib._3rear2 = function() {
	this.initialize(img._3rear2);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,360,150);


(lib._3right = function() {
	this.initialize(img._3right);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,154,273);


(lib.Bitmap1 = function() {
	this.initialize(img.Bitmap1);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,241,401);// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.Tween2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib._2grass1();
	this.instance.parent = this;
	this.instance.setTransform(-229,-64.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-229,-64.5,458,129);


(lib.Tween1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib._2grass1();
	this.instance.parent = this;
	this.instance.setTransform(-229,-64.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-229,-64.5,458,129);


(lib.t3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgOBTQgFgFAAgIQAAgJAFgGQAGgEAIAAQAJAAAGAEQAFAGAAAJQAAAIgFAFQgGAGgJAAQgIAAgGgGgAgJAiIgHgoIAAhSIAhAAIAABSIgHAog");
	this.shape.setTransform(130.7,29.3);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgfA+QgHgDgFgEQgFgFgCgHQgDgGAAgJQAAgLAFgIQAFgIAKgEQAKgFANgCQAMgBARAAQABgOgDgGQgCgDgEgBQgEgCgHAAIgUACQgLACgHADIgHgYQAKgEANgDQAOgDAOAAQANAAAJADQAJAEAFAFQAFAGACAIQACAIAAAKIgBAVIAAAWIAAAVQABAKADAJIgaAAIgGgRIgBAAQgFAHgJAGQgIAGgOAAQgIAAgIgDgAgHAKQgGACgDADQgDADAAAFQAAAHAEAEQAEAEAHAAQAJAAAFgEQAGgFADgFIAAgQIgPAAQgGAAgFACg");
	this.shape_1.setTransform(120.1,31.6);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AARA+Igeg0IgIAAIAAA0IggAAIAAh8IAgAAIAAA1IAHgCIAdgzIAiAAIgeAwIgMAKIANAJIAiA5g");
	this.shape_2.setTransform(108.9,31.7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AAVBYIAAg5IABgSIAAAAIgLASIgrA5IgVAAIAAh8IAhAAIAAA6IgCARIABAAIAKgSIAsg5IAVAAIAAB8gAgMgzQgHgBgGgEQgGgEgEgGQgDgGgCgIIAcgHQABAJAEAFQAEAEAGAAQAHAAAEgEQAEgFACgJIAZAHQgCAHgEAGQgDAHgGADQgGAFgHABQgHACgIAAQgHAAgHgCg");
	this.shape_3.setTransform(95.2,29.1);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgfA+QgHgDgFgEQgFgFgCgHQgDgGAAgJQAAgLAFgIQAFgIAKgEQAKgFANgCQAMgBARAAQABgOgDgGQgCgDgEgBQgEgCgHAAIgUACQgLACgHADIgHgYQAKgEANgDQAOgDAOAAQANAAAJADQAJAEAFAFQAFAGACAIQACAIAAAKIgBAVIAAAWIAAAVQABAKADAJIgaAAIgGgRIgBAAQgFAHgJAGQgIAGgOAAQgIAAgIgDgAgHAKQgGACgDADQgDADAAAFQAAAHAEAEQAEAEAHAAQAJAAAFgEQAGgFADgFIAAgQIgPAAQgGAAgFACg");
	this.shape_4.setTransform(81.9,31.6);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AAzA+Igag0IgKAAIAAA0IgfAAIAAg2IgJADIgZAzIglAAIAhg5IAIgGIgMgJIgag0IAjAAIAWA0IALAAIAAg0IAfAAIAAA1IAJgCIAYgzIAiAAIgcA0IgJAHIANAJIAeA4g");
	this.shape_5.setTransform(67.3,31.7);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgqBUIAGgaIAIABQAGAAAFgFQAFgFADgMIg0h8IAnAAIAWBGIAEASIACAAIADgSIAThGIAiAAIgmBwIgJAZQgFAMgFAIQgFAJgGAEQgGAFgJAAQgNAAgIgEg");
	this.shape_6.setTransform(52.7,34.2);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("Ag7A8IAFgbIAHACQAFAAAEgFQAEgEACgLQADgLACgSIACgwIBUAAIAAB8IgfAAIAAhfIgaAAIgCAiQgCARgEAOQgFAOgHAJQgIAIgMAAQgOAAgHgDg");
	this.shape_7.setTransform(39.4,31.7);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AAWBAIAAgvIgOADIgXAsIgnAAIAYgnIAMgJQgMgCgIgKQgEgEgCgGQgCgGAAgHQAAgLAEgJQAEgIAHgGQAIgFALgDQAMgCAPAAIAWABIASADIAAB7gAgGgfQgHAFAAAJQABAKAGAEQAGAEAOAAIAIgBIAAgiIgGgBIgGgBQgKAAgGAFg");
	this.shape_8.setTransform(146.6,8.1);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgfA+QgHgDgFgEQgFgFgCgHQgDgGAAgJQAAgLAFgIQAFgIAKgEQAKgFANgCQAMgBARAAQABgOgDgGQgCgDgEgBQgEgCgHAAIgUACQgLACgHADIgHgYQAKgEANgDQAOgDAOAAQANAAAJADQAJAEAFAFQAFAGACAIQACAIAAAKIgBAVIAAAWIAAAVQABAKADAJIgaAAIgGgRIgBAAQgFAHgJAGQgIAGgOAAQgIAAgIgDgAgHAKQgGACgDADQgDADAAAFQAAAHAEAEQAEAEAHAAQAJAAAFgEQAGgFADgFIAAgQIgPAAQgGAAgFACg");
	this.shape_9.setTransform(134.4,8.2);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AAUA+IAAgwIgnAAIAAAwIghAAIAAh8IAhAAIAAAvIAnAAIAAgvIAhAAIAAB8g");
	this.shape_10.setTransform(121.8,8.3);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AAUA+IAAgwIgnAAIAAAwIghAAIAAh8IAhAAIAAAvIAnAAIAAgvIAhAAIAAB8g");
	this.shape_11.setTransform(108.4,8.3);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgoAxQgHgKgEgMQgDgMAAgPQAAggAPgQQAQgRAcAAQAJAAAKACQAIADAIAGQAGAGAEAJQAFAKAAAOIgBAMIgCALIhJAAQAAAQAIAIQADAEAGACQAFACAIAAQALAAAHgDIANgGIALAVQgIAFgMAFQgOAEgOAAQgdAAgOgRgAgNgfQgHAHgBANIAtAAQABgHgBgFQgBgFgCgDQgGgIgLAAQgMAAgFAIg");
	this.shape_12.setTransform(95.3,8.3);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgeBAIgVgCIAAh8IAWgBIAagBQAaAAAMAJQAMAHAAAQQAAAJgFAIQgFAJgLADIAAABQAOACAFAIQAHAIAAALQgBAJgDAHQgEAIgHAEQgOAJgfAAgAgTAlIAHABIAHAAQANAAAFgDQAGgEAAgIQAAgGgFgEQgFgFgLAAIgRAAgAgNglIgGAAIAAAbIARAAQAIAAAEgFQAGgDAAgHQgBgFgEgEQgEgDgKAAg");
	this.shape_13.setTransform(83,8.3);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgPA+IAAhfIgkAAIAAgdIBnAAIAAAdIgjAAIAABfg");
	this.shape_14.setTransform(71.1,8.3);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgRA9QgLgEgGgJQgHgJgDgMQgCgMAAgPQAAgeAOgSQAHgIAKgFQALgEAMAAQAOAAAIACQAJACAGAEIgHAbIgMgFIgNgBQgGAAgFACQgFACgDAFQgHAJAAASQAAAIACAHQACAHADAEQADAFAFADQAGADAHAAQAIAAAGgCIAKgFIAIAZQgIAFgKADQgLADgLAAQgOAAgKgFg");
	this.shape_15.setTransform(60.7,8.3);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgYBYQgLgFgIgJQgPgUAAgpQAAgUACgPQADgQAFgKQAEgLAHgGQAGgGAIgEQAIgDAJgCIASgCIAWgDQAJgCAFgFIABAdQgFAFgJACIgZACQgKABgGACQgHABgGAFQgFAEgDAIQgDAJgBANIAAAAQAHgLAKgFQAKgFANAAQAXAAANAOQAHAHADALQAEAJAAAPQAAARgEANQgEANgIAIQgPASgcAAQgNAAgLgFgAgSAEQgHAIAAAQQAAAQAHALQAGAKAMAAQAHAAAFgCQAEgDADgEQADgFACgHQABgHAAgJQAAgIgBgGIgEgLQgGgHgNAAQgMAAgHAIg");
	this.shape_16.setTransform(48.4,5.6);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgZA9QgLgEgHgJQgIgJgDgMQgEgMAAgPQAAgPAEgMQAEgMAIgJQAHgIALgFQALgEANAAQAPAAALAEQALAGAHAIQAIAJADAMQAEAMAAAOQAAAggQARQgHAIgLAFQgLAEgOAAQgOAAgLgFgAgSgcQgDAEgCAHQgCAIAAAJQAAAIACAIIAEALQAEAGAEACQAFADAGAAQANAAAGgJQADgEACgIQABgHAAgKQAAgHgBgIIgEgMQgGgKgOAAQgLgBgHAKg");
	this.shape_17.setTransform(35,8.3);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgMBWQgPgEgLgMQgFgFgEgHQgFgHgDgJQgGgRAAgZQAAgZAHgRQAEgJAEgHQAFgHAFgFQAMgLAOgEQANgFAOAAQAPAAAKACQALACAGACIgGAeQgGgDgIgBQgHgBgMAAQgLgBgHAEQgIAEgGAHQgNAPAAAeQAAAOADALQADALAGAIQAGAHAJAFQAIAEANAAQAKABAIgDQAIgCAGgEIAHAcQgIAGgNACQgMADgNAAQgTgBgJgEg");
	this.shape_18.setTransform(21.5,5.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.t3, new cjs.Rectangle(12.3,-10,143.2,56.8), null);


(lib.t2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AAlA+IAAg5IADgZIgCAAIgKAUIgXAoIgLAAIgagoIgJgUIgCAAIADAZIAAA5IgcAAIAAh8IAhAAIAdAvIAGAPIABAAIAIgPIAagvIAiAAIAAB8g");
	this.shape.setTransform(166.9,31.7);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgZA9QgLgEgHgJQgIgJgDgMQgEgMAAgPQAAgPAEgMQAEgMAIgJQAHgIALgFQALgEANAAQAPAAALAEQALAGAHAIQAIAJADAMQAEAMAAAOQAAAggQARQgHAIgLAFQgLAEgOAAQgOAAgLgFgAgSgcQgDAEgCAHQgCAIAAAJQAAAIACAIIAEALQAEAGAEACQAFADAGAAQANAAAGgJQADgEACgIQABgHAAgKQAAgHgBgIIgEgMQgGgKgOAAQgLgBgHAKg");
	this.shape_1.setTransform(151.9,31.7);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AAzA+Igag0IgKAAIAAA0IgfAAIAAg2IgJADIgaAzIgkAAIAhg5IAIgGIgMgJIgag0IAjAAIAWA0IALAAIAAg0IAfAAIAAA1IAJgCIAXgzIAjAAIgcA0IgJAHIANAJIAeA4g");
	this.shape_2.setTransform(136.5,31.7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgfA+QgHgDgFgEQgFgFgCgHQgDgGAAgJQAAgLAFgIQAFgIAKgEQAKgFANgCQAMgBARAAQABgOgDgGQgCgDgEgBQgEgCgHAAIgUACQgLACgHADIgHgYQAKgEANgDQAOgDAOAAQANAAAJADQAJAEAFAFQAFAGACAIQACAIAAAKIgBAVIAAAWIAAAVQABAKADAJIgaAAIgGgRIgBAAQgFAHgJAGQgIAGgOAAQgIAAgIgDgAgHAKQgGACgDADQgDADAAAFQAAAHAEAEQAEAEAHAAQAJAAAFgEQAGgFADgFIAAgQIgPAAQgGAAgFACg");
	this.shape_3.setTransform(121.4,31.6);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgPA+IAAhfIgkAAIAAgdIBnAAIAAAdIgiAAIAABfg");
	this.shape_4.setTransform(110.2,31.7);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgeA/QgNgCgGgEIAIgZQAFADAIABQAJACAHAAQAIAAAFgBQAGgCADgDQAEgEACgFQACgFAAgIIguAAIAAgVIAtAAQAAgNgIgGQgGgIgNABQgJAAgIABIgMAGIgJgYQAIgFALgDQALgDAOAAQAbAAAOARQAGAIAEAMQADAMABAQQAAAhgQARQgHAHgMAFQgKAEgNAAQgMAAgLgDg");
	this.shape_5.setTransform(99.2,31.7);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgfAOIAAgbIA+AAIAAAbg");
	this.shape_6.setTransform(89.1,30.7);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AAuBNIgEgdIhTAAIgEAdIgYAAIAAg6IAQAAIAEgJIAHgRQADgLACgRQACgSAAgXIBWAAIAABfIATAAIAAA6gAgIgdIgEAUIgEAQIgFAOIAoAAIAAhFIgaAAg");
	this.shape_7.setTransform(77.3,33.1);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AAUA+IAAgwIgnAAIAAAwIghAAIAAh8IAhAAIAAAvIAnAAIAAgvIAhAAIAAB8g");
	this.shape_8.setTransform(63.7,31.7);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgqBUIAGgaIAIABQAGAAAFgFQAFgFADgMIg0h8IAnAAIAWBGIAEASIACAAIADgSIAThGIAiAAIgmBwIgJAZQgFAMgFAIQgFAJgGAEQgGAFgJAAQgNAAgIgEg");
	this.shape_9.setTransform(51,34.2);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgfA+QgHgDgFgEQgFgFgCgHQgDgGAAgJQAAgLAFgIQAFgIAKgEQAKgFANgCQAMgBARAAQABgOgDgGQgCgDgEgBQgEgCgHAAIgUACQgLACgHADIgHgYQAKgEANgDQAOgDAOAAQANAAAJADQAJAEAFAFQAFAGACAIQACAIAAAKIgBAVIAAAWIAAAVQABAKADAJIgaAAIgGgRIgBAAQgFAHgJAGQgIAGgOAAQgIAAgIgDgAgHAKQgGACgDADQgDADAAAFQAAAHAEAEQAEAEAHAAQAJAAAFgEQAGgFADgFIAAgQIgPAAQgGAAgFACg");
	this.shape_10.setTransform(38.6,31.6);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("Ag3BZIAAiuIAXAAIAEAPIABAAQAHgJAJgFQAIgEAMAAQAMAAAJADQAJAEAGAIQALAOAAAhQAAAQgDAMQgEANgHAJQgIAJgKAFQgLAFgNAAIgMgBIgLgEIAAAzgAgPg4QgEAFgEAJIAAAzIAIAFQAEABAHAAQAGAAAFgCQAGgDADgFQADgFACgHQACgIAAgLQAAgIgCgHQgBgGgDgFQgFgJgMAAQgJAAgGAFg");
	this.shape_11.setTransform(26.2,34);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgnA+IAAh8IBPAAIAAAdIguAAIAABfg");
	this.shape_12.setTransform(15.2,31.7);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgRA9QgLgEgGgJQgHgJgDgMQgCgMAAgPQAAgeAOgSQAHgIAKgFQALgEAMAAQAOAAAIACQAJACAGAEIgHAbIgMgFIgNgBQgGAAgFACQgFACgDAEQgHAJAAATQAAAIACAHQACAHADAEQADAFAFADQAGADAHAAQAIAAAGgCIAKgFIAIAZQgIAFgKADQgLADgLAAQgOAAgKgFg");
	this.shape_13.setTransform(-1.8,31.7);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("Ag1A/IgUgBIAAh8IAhAAIAAAsIAMgBIALgBQANAAAIADQAIADAFAFQAFAGACAGQACAHABAIQgBAMgDAIQgCAIgHAGQgHAGgKADQgLACgPAAgAgoAEIAAAfIAOABQAMAAAEgEQAEgEABgJQgBgIgEgEQgEgEgLAAQgIAAgHABgAApA+IAAh8IAhAAIAAB8g");
	this.shape_14.setTransform(129.7,8.3);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("Ag3BZIAAiuIAYAAIADAPIABAAQAGgJAKgFQAIgEAMAAQAMAAAJADQAJAEAFAIQAMAOAAAhQAAAQgEAMQgDANgHAJQgIAJgKAFQgLAFgNAAIgMgBIgKgEIAAAzgAgPg4QgEAFgDAJIAAAzIAHAFQAEABAHAAQAGAAAFgCQAGgDADgFQADgFACgHQACgIAAgLQAAgIgBgHQgCgGgDgFQgFgJgMAAQgJAAgGAFg");
	this.shape_15.setTransform(114.5,10.6);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AAVA+IAAg4IABgRIAAAAIgLARIgrA4IgVAAIAAh8IAhAAIAAA8IgCAQIABAAIAKgRIAsg7IAVAAIAAB8g");
	this.shape_16.setTransform(100.6,8.3);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgPA+IAAhfIgkAAIAAgdIBnAAIAAAdIgjAAIAABfg");
	this.shape_17.setTransform(88.6,8.3);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("Ag3BZIAAiuIAXAAIAEAPIABAAQAHgJAJgFQAJgEALAAQAMAAAJADQAIAEAHAIQALAOAAAhQAAAQgDAMQgEANgHAJQgIAJgKAFQgLAFgNAAIgNgBIgKgEIAAAzgAgPg4QgEAFgEAJIAAAzIAIAFQAEABAHAAQAGAAAFgCQAGgDADgFQADgFACgHQACgIAAgLQAAgIgCgHQgBgGgCgFQgGgJgMAAQgJAAgGAFg");
	this.shape_18.setTransform(76.9,10.6);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgfA+QgHgDgFgEQgFgFgCgHQgDgGAAgJQAAgLAFgIQAFgIAKgEQAKgFANgCQAMgBARAAQABgOgDgGQgCgDgEgBQgEgCgHAAIgUACQgLACgHADIgHgYQAKgEANgDQAOgDAOAAQANAAAJADQAJAEAFAFQAFAGACAIQACAIAAAKIgBAVIAAAWIAAAVQABAKADAJIgaAAIgGgRIgBAAQgFAHgJAGQgIAGgOAAQgIAAgIgDgAgHAKQgGACgDADQgDADAAAFQAAAHAEAEQAEAEAHAAQAJAAAFgEQAGgFADgFIAAgQIgPAAQgGAAgFACg");
	this.shape_19.setTransform(63.4,8.2);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgeBAIgVgCIAAh8IAWgBIAagBQAaAAAMAJQAMAHAAAQQAAAJgFAIQgFAJgLADIAAABQAOACAFAIQAHAIAAALQgBAJgDAHQgEAIgHAEQgOAJgfAAgAgTAlIAHABIAHAAQANAAAFgDQAGgEAAgIQAAgGgFgEQgFgFgLAAIgRAAgAgNglIgGAAIAAAbIARAAQAIAAAEgFQAGgDAAgHQgBgFgEgEQgEgDgKAAg");
	this.shape_20.setTransform(51.5,8.3);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AAaBXIgyhKIgJAAIAABKIgiAAIAAitIAiAAIAABNIAIgDIAvhKIAnAAIgzBJIgNAKIAOAIIA5BSg");
	this.shape_21.setTransform(37.7,5.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.t2, new cjs.Rectangle(-9.5,-10,186.8,56.8), null);


(lib.t1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("Ag3BZIAAiuIAXAAIAEAPIABAAQAHgJAJgFQAIgEAMAAQAMAAAJADQAJAEAFAIQAMAOAAAhQAAAQgDAMQgEANgHAJQgIAJgKAFQgLAFgNAAIgMgBIgLgEIAAAzgAgPg4QgEAFgEAJIAAAzIAIAFQAEABAHAAQAGAAAFgCQAGgDADgFQADgFACgHQACgIAAgLQAAgIgCgHQgBgGgDgFQgFgJgMAAQgJAAgGAFg");
	this.shape.setTransform(121.6,34);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AAVA+IAAg4IABgRIAAAAIgLARIgrA4IgVAAIAAh8IAhAAIAAA8IgCAQIABAAIAKgRIAsg7IAVAAIAAB8g");
	this.shape_1.setTransform(107.7,31.7);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgPA+IAAhfIgkAAIAAgdIBnAAIAAAdIgjAAIAABfg");
	this.shape_2.setTransform(95.7,31.7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("Ag3BZIAAiuIAXAAIAEAPIABAAQAHgJAIgFQAJgEAMAAQAMAAAJADQAIAEAHAIQALAOAAAhQAAAQgDAMQgEANgIAJQgHAJgLAFQgKAFgNAAIgNgBIgKgEIAAAzgAgPg4QgFAFgDAJIAAAzIAIAFQAEABAHAAQAGAAAFgCQAGgDADgFQADgFACgHQACgIAAgLQAAgIgCgHQgBgGgCgFQgGgJgMAAQgJAAgGAFg");
	this.shape_3.setTransform(84,34);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgfA+QgHgDgFgEQgFgFgCgHQgDgGAAgJQAAgLAFgIQAFgIAKgEQAKgFANgCQAMgBARAAQABgOgDgGQgCgDgEgBQgEgCgHAAIgUACQgLACgHADIgHgYQAKgEANgDQAOgDAOAAQANAAAJADQAJAEAFAFQAFAGACAIQACAIAAAKIgBAVIAAAWIAAAVQABAKADAJIgaAAIgGgRIgBAAQgFAHgJAGQgIAGgOAAQgIAAgIgDgAgHAKQgGACgDADQgDADAAAFQAAAHAEAEQAEAEAHAAQAJAAAFgEQAGgFADgFIAAgQIgPAAQgGAAgFACg");
	this.shape_4.setTransform(70.5,31.6);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgeBAIgVgCIAAh8IAWgBIAagBQAbAAALAJQAMAHAAAQQAAAJgFAIQgFAJgLADIAAABQAOACAFAHQAHAJAAALQgBAJgDAIQgEAHgHAEQgOAJgfAAgAgTAlIAHABIAHAAQANAAAFgDQAGgEAAgIQAAgGgFgEQgFgFgLAAIgRAAgAgNglIgGAAIAAAbIARAAQAIAAAEgFQAGgDAAgHQgBgFgEgEQgEgDgKAAg");
	this.shape_5.setTransform(58.6,31.7);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AARA+Igeg0IgIAAIAAA0IggAAIAAh8IAgAAIAAA1IAHgCIAcgzIAjAAIgeAwIgMAKIANAJIAjA5g");
	this.shape_6.setTransform(46.7,31.7);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgPA+IAAhfIgkAAIAAgdIBnAAIAAAdIgjAAIAABfg");
	this.shape_7.setTransform(160.5,8.3);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgfA+QgHgDgFgEQgFgFgCgHQgDgGAAgJQAAgLAFgIQAFgIAKgEQAKgFANgCQAMgBARAAQABgOgDgGQgCgDgEgBQgEgCgHAAIgUACQgLACgHADIgHgYQAKgEANgDQAOgDAOAAQANAAAJADQAJAEAFAFQAFAGACAIQACAIAAAKIgBAVIAAAWIAAAVQABAKADAJIgaAAIgGgRIgBAAQgFAHgJAGQgIAGgOAAQgIAAgIgDgAgHAKQgGACgDADQgDADAAAFQAAAHAEAEQAEAEAHAAQAJAAAFgEQAGgFADgFIAAgQIgPAAQgGAAgFACg");
	this.shape_8.setTransform(148.8,8.2);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AAmA+IAAg5IACgZIgBAAIgKAUIgYAoIgKAAIgagoIgKgUIgBAAIACAZIAAA5IgcAAIAAh8IAiAAIAdAvIAFAPIABAAIAHgPIAbgvIAiAAIAAB8g");
	this.shape_9.setTransform(134.6,8.3);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("Ag3BZIAAiuIAXAAIAEAPIABAAQAHgJAJgFQAIgEAMAAQAMAAAJADQAJAEAFAIQAMAOAAAhQAAAQgDAMQgEANgHAJQgIAJgKAFQgLAFgNAAIgMgBIgLgEIAAAzgAgPg4QgEAFgEAJIAAAzIAIAFQAEABAHAAQAGAAAFgCQAGgDADgFQADgFACgHQACgIAAgLQAAgIgCgHQgBgGgCgFQgGgJgMAAQgJAAgGAFg");
	this.shape_10.setTransform(119.8,10.6);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgZA9QgLgEgHgJQgIgJgDgMQgEgMAAgPQAAgPAEgMQAEgMAIgJQAHgIALgFQALgEANAAQAPAAALAEQALAGAHAIQAIAJADAMQAEAMAAAOQAAAggQARQgHAIgLAFQgLAEgOAAQgOAAgLgFgAgSgcQgDAEgCAHQgCAIAAAJQAAAIACAIIAEALQAEAGAEACQAFADAGAAQANAAAGgJQADgEACgIQABgHAAgKQAAgHgBgIIgEgMQgGgKgOAAQgLgBgHAKg");
	this.shape_11.setTransform(106,8.3);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgPBxIAAgxIgJACIgIAAQgMAAgIgEQgJgEgGgIQgMgRAAghQAAgfANgQQAOgRAZAAIAMABIAAgwIAfAAIAAAwIAIgBIAHAAQAMAAAJADQAKAFAGAHQAGAHADAMQADAMABARQAAAPgEAMQgDAMgHAJQgGAKgKAEQgJAFgMAAIgHgBIgHgBIAAAxgAATgmIgFABIAABNIAFAAIAGABQAGAAAEgDQAEgCADgFQAGgKAAgWQAAgKgBgIQgCgHgDgDQgFgKgOABgAghgkQgFACgDAFQgDAEgCAHQgBAJAAAJQAAAKABAHQACAIADAFQAFALAMAAIAFgBIAFgBIAAhMIgJgBQgGgBgEADg");
	this.shape_12.setTransform(90.6,8.3);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AAVBYIAAg5IABgSIAAAAIgLASIgrA5IgVAAIAAh8IAhAAIAAA6IgCARIABAAIAKgSIAsg5IAVAAIAAB8gAgMgzQgHgBgGgEQgGgEgEgGQgDgGgCgIIAcgHQABAJAEAFQAEAEAGAAQAHAAAEgEQAEgFACgJIAZAHQgCAHgEAGQgDAHgGADQgGAFgHABQgHACgIAAQgHAAgHgCg");
	this.shape_13.setTransform(68.7,5.7);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("Ag1A/IgTgBIAAh8IAgAAIAAAsIAMgBIALgBQANAAAHADQAJADAFAFQAFAGADAGQABAHAAAIQABAMgDAIQgDAIgHAGQgHAGgJADQgMACgPAAgAgoAEIAAAfIAOABQALAAAFgEQAFgEgBgJQABgIgFgEQgFgEgKAAQgJAAgGABgAApA+IAAh8IAgAAIAAB8g");
	this.shape_14.setTransform(53.2,8.3);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgeBAIgUgCIAAh8IAUgBIAbgBQAbAAALAJQAMAHAAAQQAAAJgFAIQgFAJgLADIAAABQANACAHAIQAFAIAAALQABAJgEAHQgDAIgIAEQgPAJgeAAgAgTAlIAGABIAIAAQAMAAAGgDQAGgEAAgIQAAgGgFgEQgFgFgMAAIgQAAgAgNglIgGAAIAAAbIARAAQAHAAAGgFQAEgDAAgHQABgFgFgEQgEgDgLAAg");
	this.shape_15.setTransform(38.4,8.3);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgZA9QgLgEgHgJQgIgJgDgMQgEgMAAgPQAAgPAEgMQAEgMAIgJQAHgIALgFQALgEANAAQAPAAALAEQALAGAHAIQAIAJADAMQAEAMAAAOQAAAggQARQgHAIgLAFQgLAEgOAAQgOAAgLgFgAgSgcQgDAEgCAHQgCAIAAAJQAAAIACAIIAEALQAEAGAEACQAFADAGAAQANAAAGgJQADgEACgIQABgHAAgKQAAgHgBgIIgEgMQgGgKgOAAQgLgBgHAKg");
	this.shape_16.setTransform(25.1,8.3);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AAgBXIAAhJIg/AAIAABJIgiAAIAAitIAiAAIAABHIA/AAIAAhHIAiAAIAACtg");
	this.shape_17.setTransform(10.2,5.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.t1, new cjs.Rectangle(0,-10,167.8,56.8), null);


(lib.tlogo1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AJLBYIgHgCIgEgFIgCgGIgBgIIABgKIAFgIIADgDIAKgEIAQAQIAIgNIANgtIAHg/IgFgEIgSgDIAAgOICEAAIAAAOIgOACIgDAEIAACCIADAEIAOABIAAAQIhPAAIAAgQIAPgBIAEgEIAAiEIgcAAIgIBLIgJAhIgLAYQgGAKgGADQgGAHgFABQgDABgIAAgAG7BXIAAgQIARgBIABgDIgNgnIgxAAIgMAnIACADIAPABIAAAQIg4AAIAAgQIAPgBIA2ibIAhAAIA3CaIAOACIAAAQgAG6AMIgTg5IgTA5IAmAAgACvBXIAAgQIAPgBIAFgEIAAiEIgXAAIgEACIgEAfIgUAAIAAgzICQAAIAAAzIgTAAIgGgfIgEgCIgWAAIAACEIAEAEIAPABIAAAQgAhABXIAAgQIAPgBIAEgEIAAiCIgCgEIgRgCIAAgOIBKAAIAWACQAFABAKADIAJADIAMALQAEAGADAJIABARIAAAPIgFANIgGAIIgFAFQgFAFgJADQgGAEgLADIgTAAIgNAAIAAAqIADAEIARABIAAAQgAgDAHIAJAAIAJgCIAHgFIAGgHIAEgLIAAgMIgCgRIgDgJIgFgFIgHgEIgSgBgAjMBXIAAgQIAPgBIADgDIgMgnIgyAAIgMAnIACADIAQABIAAAQIg5AAIAAgQIAPgBIA2ibIAiAAIA2CaIAOACIAAAQgAjNAMIgTg5IgSA5IAlAAgAn/BXIAAgQIAQgBIADgEIAAiCIgDgEIgQgCIAAgOIBVAAIAbADIALAGQAIAFADAIQADAGAAALIgBANQgBAGgGAGIgNAKQgEAEgJACIANACIAJACIAIAFIAHAHIAEAJQACAFAAAKQAAAPgEAIQgDAIgIAGIgNAIIggAGgAnDBGIANAAIANgCIALgIIAEgIIACgIIAAgGIgBgKQAAgFgDgDQgBgEgGgDIgHgEIgHgCIgSAAgAnDgKIANAAIAKgDIAGgGQAEgEAAgFIADgMIgEgQIgEgGIgHgDIgIgCIgNAAgAp+BXIAAgLIgTgxQAAgEgEgDQgCgFgCgCIgHgEIgFgBIgGAAIAAA6IAEAEIANABIAAAQIhOAAIAAgQIAPgBIAFgEIAAiCIgFgEIgPgCIAAgOIBOAAIAAAOIgNACIgEAEIAAA2IAPAAIAEgBIAGgDIAJgQIARgqIAHgJIAIgFIAMgCIAJACIAGADIADADQADACACAFIABAJIgCALQgDAFgEADQgDAEgHAAIgSgRIgFAIIgIAXIgFALIgGAIIgGAFIAAABQAFAAAFACIAJAHIAIAIIAEAJIAFAHIAOAjIAFAEIARABIAAAQg");
	this.shape.setTransform(153.5,-0.6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("ADwBvQgQgGgJgJIgLgLIgJgQQgFgKgCgKQgCgGAAgRIABgPIADgSIAJgTIAQgQIAPgLIATgGIAYgCIASABQAJAAAKAGIAQAKQAGAEANAQIAKAYQADAMAAAOQAAAMgDANQgBAKgIAOQgFAJgHAHIgEADQgGAGgLAFQgLAHgJABQgKADgMAAQgQAAgPgFgAEHgpIgIADIgKALIgHAOIgFASIgBAWIACAXIAFATIAIANIAIAJIAIAEIAJABIAIgBIAJgEIAJgIIAHgQIAHgrIgCgWIgFgRIgGgLQgEgHgFgFIgKgDIgIgBgAgwByIgHgDIgGgKIgCgJIADgKIADgHIAEgDIALgFIAPAQIAHgMIAIgTQAFgMABgOIADgPIADgxIgDgDIgTgDIAAgOICEAAIAAAOIgPACIgEADIAACCIAEAEIAPABIAAAQIhRAAIAAgQIARgBIADgEIAAiEIgcAAIgFA6IgMAyQgFAQgFAIQgEAJgIAFIgKAHQgEACgIAAgAIbBwIAAgQIAPgBIADgEIAAhfIg+BWIAAAJIADAEIAOABIAAAQIhOAAIAAgQIAPgBIAEgEIAAiCIgEgDIgPgCIAAgOIBOAAIAAAOIgOACIgDADIAABeIA+hWIAAgIIgDgDIgPgCIAAgOIBNAAIAAAOIgOACIgDADIAACCIADAEIAOABIAAAQgAjLBwIAAgQIAOgBIADgEIAAhfIg+BWIAAAJIAEAEIAOABIAAAQIhOAAIAAgQIAOgBIAFgEIAAiCIgFgDIgOgCIAAgOIBOAAIAAAOIgOACIgEADIAABeIA+hWIAAgIIgDgDIgOgCIAAgOIBNAAIAAAOIgOACIgEADIAACCIAEAEIAOABIAAAQgAmxBwIAAgLIgUg6IgKgJIgFgBIgHAAIAAA6IAEAEIAOABIAAAQIhLAAIAAgQIAOgBIADgEIAAg6IgFAAIgHABIgFAFIgHAKIgBAEIgPAwIAAALIg8AAIAAgQIARgBIAEgEIARgvIAJgMIAIgFQAGgDADgBIAHgBIAAgBIgHgEIgGgIQgCgCgCgIIgLggIgTASQgHAAgDgEQgEgDgDgFQgCgDAAgJIABgKIAEgFIAJgGIAKgBIALABIAIAGIAIAIIASAvIAGAKIAFACIAEACIALAAIAAg2IgDgDIgOgCIAAgOIBLAAIAAAOIgOACIgEADIAAA2IALAAIAEgCIAFgCIAFgGIASgvIAJgNIAIgEQADgCAJAAIAJABQAFACAAABIAFADIADAFIACAKIgCAMIgHAIQgEAEgGAAIgTgSIgDAGIgHAaIgLASIgGAEIAAABIAHABIAQAJIAJAMIASAvIAEAEIAQABIAAAQgAH5hIIgOgDIgHgDQgIgDgBgEIgEgIIAAgFQAAgFACgEIAGgFQAFgDAHAAIAIACQADgBAEAFIAAAVIALADIASAAIAKgDIAAgVQAEgFAEABIAIgCQAIAAADADQAFABACAEIACAJIgBAFIgDAIIgJAHIgIADIgNADIgVACIgVgCg");
	this.shape_1.setTransform(-3,-3.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.tlogo1, new cjs.Rectangle(-64.6,-14.8,292.7,23.3), null);


(lib.tlogo = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AruDxQgdgJgQgdQgNgaAAgdQAAgUAFgOQAEgNAIgJQANgQAUgFQATgFASAGQAKAFAGAEQASAOABAZQABAHgDAHQgCAIgEAFQgIAKgOAAQgIABgJgDIgLgGQgFgCgDAAQgBAAgBAAQAAABgBAAQAAAAgBABQAAAAAAABQgCACgBAEQgCAIADAGQAGALAOAEQAQAEASgFQASgFAPgXQAMgSAFgWIh7knQgGgPgJgKQgIgKgGgFIgEgCIgHgDIgEgFIgDgGIgBgEQAAgGAGAAIBvAAQAEAAACAFIADALQAAADgDACIgEACQgCABAAAGIgBAHQABAMAFAMIBUDJIBBjUQADgJgBgKIgBgIQgCgDgFAAIgBAAQgGgCABgFIAAAAIABgHQABgGAFAAIBrAAIADABQAFADgCAFIgEAHIgBADIgFACQgDABgEAEIgHAIQgIAKgCAJIhPD4QgQA0gRAtQgJAYgPATQgOAUgSALQgQALgSAEQgTAEgSAAQgPAAgQgFgASrDsQgHAAAAgGIAAgKQAAgCADgDQAFABADgIQAIgOgDgUIgPhlIgLACIgbAwQgDAFgFgCQgBgBAAAAQgBAAAAgBQAAAAAAAAQgBgBAAAAIgVglIgWAEIgKBTIAAAAQgFAlAKADIACAAQAFABAAAGIAAAJQAAAGgGAAIhZAAQgGAAAAgGIACgLQAAgBABgBQAAAAAAgBQABAAAAAAQABgBAAAAIAEgCIAEgEQADgEAEgIQAFgLACgOIAslhIAAgBQAEgogLAAQgFgBAAgGIAAgJQAAgGAGAAICtAAQAGAAAAAGIAAAKQAAADgEADQgQAJAEAgIA1FiQACAOAGAKIAFAJIAGAGIAHADQACACABADIADAJQABAGgFACgAR0jSQgGAHgDAWIgcDlIAKgCIAbgwQAEgFAFADIACADIAVAkIALgCIggjWQgDgVgGgIIgBgBgANCDsQgGgBABgGIABgJQABgGAGAAIACgBQAEgCAGgNQAEgJAAgMIAAAAIAAhUQAAgcgDgJQgIgVgOgMQgPgMgNABIgDACQgLAGgEAHQAHgBAGACQAIAEADAMIAAAAQADAMgGAIQgFAHgJAEIgBAAQgGABgFAAQgMgBgJgHQgFgEgEgGIAABzQAAANAFALIAFAKQADAFACABIAFACQACABABAEIABAJQABAGgGABIhvAAQgGAAAAgGIAAgBIABgKIACgEQAGABAFgJIAFgKQAEgJAAgPIAAljQAAgOgEgKQgFgOgFgBQgIgEAAgEIgBgJQgBgGAGgBIBvAAQAGAAAAAGIAAACIgBAJQgBAEgHADQgEABgGAOQgFAMAAAMIAAC4QAGgJATgWQAggjAPghQALgZAFgYQAFgbgCgWQgBgLgEgIQgEgGgDgBQgHgDgBgEIgBgJIAAgCQAAgGAGAAIBvAAQAGABAAAGIgBAAIgBAJQAAADgEADQgGADgCADIgGAKQgCAGgEAfIgCAUQgDARgGAQQgHAUgJAPQgMAUgOAQIAAABIgWAZQAcAHAUANQAZARAHAYQAIAZAAA7IAAAQQAAAiACALQACAKAEAHIAEAGQACAEACAAIAEACQADABABADIABAKIAAABQAAAGgGAAgAEtDlIACgJQAAgBAAAAQAAgBAAgBQAAAAABAAQAAgBABAAIAEgDQADgBADgEIAGgLQAEgLAAgNIAAljQAAgHgBgGIgCgIQgKAAgGACQgIACABAEIAEADQAEAEACAGQADAOgKAMQgMAPgYgFQgJgCgIgJQgFgHgCgGQgFgNAEgRQAFgRANgLQAKgIALgEQAOgFA9AAIAIAAIAyABQAUAAAUABQAVADASAEQAXAGATAKQASALAIAMQAVAeAAA1QAAA1gVAdQgGALgNAHIgNAIIAUAJQAQAJAIALQAWAeAAA1QAAA0gWAeQgNATgdALQgfAMgmAEIibACQgGgBABgGgAGQCtIABAMIACAHIAegCQAegDAPgHQAQgHALgTQAIgOAAgiQAAgigIgPQgIgOgPgJQgRgLgUgGIgEgBQgRgEgHgDQgMgFgFgKgAG6ggQgBADAEACQAIADASgLQAQgLAKgTQAHgPAAgiQAAgigHgPQgKgTgPgIQgOgHgcgCIgSgCIgJAAIgCAHIgBAMIAACGQAEgIAKgFIAAgBIACAAQALgFAMADQAMAEAGAIQAFAIgDAGQgEALgKgHIgBAAQgBAAAAAAQAAAAAAAAQgBABAAAAQAAABAAAAgAAVDlQghgKgTgVQgWgWAAggIAAh4IgZgVIAAgBQgFgEAFgEIAZgWIAAh+QAAgfAWgXQATgVAhgJQAZgHAZAAQAZAAAZAHQAiAJAUAVQAVAXAAAfIAAB+IAZAXQAFAEgFADIgZAWIAAB4QAAAggVAWQgUAVgiAKQgZAHgZAAQgZAAgZgHgAA1jGQgaAMAAAhIAAEoQAAAiAaALQAIAEAKAAQAKAAAIgEQAagLAAgiIAAkoQAAghgagMQgJgEgJAAQgJAAgJAEgAjrDsQgFgBAAgGIABgJQAAgDADgCIAGgDQACgBADgGIAEgHQAFgKAAgLIAAAAQABg4gBgcQgBgcgDgJQgHgWgOgLQgPgMgOABIAAABIgDABQgLAGgDAHQAHgBAGACQAIAFADAKQACAKgEAJQgEAJgKADQgGADgIgBQgMgBgIgHQgFgEgEgGIAABzQAAANAFALIAEAIQADAHADABIAFACQADACAAADIABAJQABAGgGABIhwAAQgGAAAAgGIAAgBIACgKQABgFAFAAIACgBQAEgCAGgOQAEgLAAgNIAAljQAAgMgEgMIgFgJQgDgGgDgBIgFgCQgBgBAAAAQgBgBAAAAQAAgBAAAAQAAgBAAgBIgCgJQgBgGAHgBIBvAAQAGAAAAAGIAAACIgBAJQAAAAAAABQgBABAAAAQAAAAgBABQAAAAgBABQgCACgDAAQgDABgDAHIgEAIQgFAMAAAMIAAC4QAEgGAUgZQAigkAOggQALgaAEgXQAFgZgBgYQgBgLgEgHIgEgGIgEgDIgFgCQgCgCAAgCIgBgJIAAgCQAAgGAGAAIBvAAQAGABgBAGIgBAJQAAAEgDABQgHAEgCADIgGAKQgEAKgCAbIgCAUQgEATgFAOQgGASgLARQgLAUgOARQgJAMgNANQAcAHAUANQAZARAHAYQAIAZAAA7IAAAQQAAAiACALQABAIAFAJIAEAGQAEAGAFAAQABABAAAAQAAABABAAQAAABAAAAQAAABAAAAIACAKIAAABQAAAGgGAAgAvGDsQgGgBABgGIABgJQABgEABgBQAFABAFgIQAEgFACgFQAEgKAAgLIAAAAIABhUQgBgdgDgIQgGgSgMgMQgKgKgNgDIgCABQgLAGgDAHQAHgBAGACQADACACADQAHAIAAALQgBAMgJAGQgDADgFACIgBAAQgRAEgPgLQgFgEgEgGIAABzQAAANAFALIADAHQAEAHACABIAGADQADABAAAEIABAJQABAGgGABIhuAAQgGAAAAgGIAAgBIABgKIACgDIAGgDQADgBAEgIIADgHQAFgLAAgNIAAhzQgEAGgFAEQgIAHgMABQgLAAgJgFQgJgGgBgLQgCgKAGgJQADgEAEgDQAGgCAHABQgDgHgLgGIgCgBQgNADgKAKQgMAMgGASQgDAIgBAdIABBUIAAAAQAAALAEAKIAFAJQAEAFACABIAFACQABABABAEIABAJQABAGgGABIhvAAQgGAAAAgGIAAgBIABgKQAAAAAAgBQAAAAABgBQAAAAAAAAQAAgBABAAIAEgCQACgBADgEIAFgIQAEgHACgMQABgKAAgLIABgkQAAg7AHgZQAHgWAWgRQARgMAagIIgXgaQgOgRgMgVQgKgRgHgTQgGgQgDgSIgCgPQgDgjgGgLQgDgHgEgCQgEAAgCgCQAAgBgBAAQAAgBAAAAQgBgBAAAAQAAgBAAgBIgBgJQgBgGAGgBIBvAAQAHAAAAAGIgBACIgBAJQAAADgDABIgEACIgEAEIgCACQgMATAIAtQAEAdANAaQAOAhAhAjQATAWAFAIIAAi3QAAgMgFgMIgFgLQgDgEgDgBQAAAAgBAAQgBAAAAgBQgBAAAAAAQgBAAAAgBQgDgBAAgEIgBgJQgBgGAGgBIBuAAQAGAAAAAGIAAACIgBAJQAAADgEACQgFACgCADQgEAEgDAIQgFAMAAAMIAAC3QAFgIATgWQAigkANggQANgaAEgdQAIgvgOgTQgCgDgEgCIgEgDIgBgCIgBgJIgBgCQAAgGAHAAIBvAAQAGABgBAGIgBAJQAAABAAABQgBAAAAABQAAAAAAABQgBAAAAABIgFACQgDABgCACQgHAJgFArIgCAPQgDARgFARQgIAVgKAPQgMAVgOARIgXAaQAaAIARAMQAXARAGAWQAHAZAAA7IABAkQAAALABAKQACAMAEAHIAFAIIAEAFIAEABQADABAAADIABAKIAAABQAAAGgGAAg");
	this.shape.setTransform(131.1,24.6);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.tlogo, new cjs.Rectangle(0,0,262.3,49.3), null);


(lib.Symbol15 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgEAEQAAAAAAAAQgBgBAAAAQAAgBAAgBQAAAAAAgBQAAAAAAAAQAAgBAAgBQAAAAABgBQAAAAAAgBQABAAAAAAQABgBAAAAQABAAABAAQAAgBAAAAQADAAACACQAAABAAAAQABABAAAAQAAABAAABQAAAAAAAAQAAABAAAAQAAABAAABQAAAAgBABQAAAAAAAAQgCACgDABQAAAAAAgBQgBAAgBAAQAAAAgBgBQAAAAgBgBg");
	this.shape.setTransform(191.8,22.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AAAAUIAJgQIAGgEIgGgDIgKgQIAEgFIATAYIgSAZgAgUAUIAKgQIAFgEIgFgDIgLgQIAFgFIASAYIgRAZg");
	this.shape_1.setTransform(188.1,20);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgHAbQgEgCgDgEIgEgJIgBgMQAAgGABgGQACgEADgFQAGgHALAAIAIABIAHACIgCAIIgGgCIgHgBQgOAAAAAUIABAIQAAAEACACIAFAFQADACAEAAIAHgBIAFgDIADAHQgDACgFACQgEABgFAAQgFAAgFgCg");
	this.shape_2.setTransform(183,20.1);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AANAcIAAggIAAgHIgFAHIgYAgIgEAAIAAg2IAJAAIAAAgIgBAGIABAAIADgHIAYgfIAGAAIAAA2g");
	this.shape_3.setTransform(177.5,20.1);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgMAcIgIAAIAAg2IAIgBIALAAQAKgBAFAEQACABABAEQACACAAADQAAAEgDAEQgCAEgGABIAAABIAGABIAEACQACADABAGQAAAIgHAFQgCACgGABIgJAAgAgLAUIAFAAIAEAAQAGAAAEgBIADgDIABgFQAAgDgEgDQgDgCgGgBIgKAAgAgLgTIAAAPIALAAIADAAIADgCIACgCIACgEQAAgEgDgCQgCgBgHAAIgFAAg");
	this.shape_4.setTransform(171.9,20.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgWAnIAAhMIAGAAIACAHIAAAAQADgEAEgCQAEgCAEAAQALAAAFAGQADAEACAFIABANQAAAHgCAEQgCAGgDAEQgDADgFACQgFADgEAAIgHgBIgFgCIAAAXgAgFgeIgDADQgEACgBAGIAAAbIAFACIAGABQADAAADgCQADgBACgDQAFgFAAgKIgBgJQgBgDgCgDQgBgDgDgBQgDgBgDAAIgFAAg");
	this.shape_5.setTransform(166.2,21.1);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgIAbQgFgCgDgEIgEgJQgBgGgBgGQAAgNAHgIQADgDAFgCQADgCAGAAIAHABIAHADIAFAHQABAEAAAHIAAAHIgjAAIABAJIAEAGQABACAEACIAHABIAIgBIAGgDIADAGIgIAFQgFABgGAAQgGAAgEgCgAAOgFQAAgIgDgEQgDgDgGAAIgFABQgDABgBACQgFACgBAJIAbAAIAAAAg");
	this.shape_6.setTransform(160.3,20.1);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgHAbQgEgCgDgEIgEgJIgBgMQAAgGABgGQACgEADgFQAGgHALAAIAIABIAHACIgCAIIgGgCIgHgBQgOAAAAAUIABAIQAAAEACACIAFAFQADACAEAAIAHgBIAFgDIADAHQgDACgFACQgEABgFAAQgFAAgFgCg");
	this.shape_7.setTransform(155.1,20.1);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AAMAcIAAgZIgXAAIAAAZIgJAAIAAg2IAJAAIAAAWIAXAAIAAgWIAJAAIAAA2g");
	this.shape_8.setTransform(149.6,20.1);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgLAcIgFgEIgEgFIAAgGQAAgFABgEQACgDAEgBQADgBAGgBIAKgBIACAAIAEAAIAAgGIgBgFIgCgDIgDgCIgGAAIgCAAIgFABIgEABIgDABIgEgHQAFgCAFgBQAGgBAFAAQAGAAADABQADABACADIADAGIABAGIgBALIAAAMIAAAIIACAHIgHAAIgCgIIgBAAIgDADIgDADIgFACIgFAAIgHAAgAgBADIgFABIgEAEQAAAAgBAAQAAABAAAAQAAABAAABQAAAAAAABQgBADADADQADADAEgBIAFAAIAEgCIADgDIACgDIAAgJIgEgBIgCAAg");
	this.shape_9.setTransform(143.8,20.1);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgWAnIAAhMIAGAAIACAHIAAAAQADgEAEgCQAEgCAEAAQALAAAFAGQADAEACAFIABANQAAAHgCAEQgCAGgDAEQgDADgFACQgFADgEAAIgHgBIgFgCIAAAXgAgFgeIgDADQgEACgBAGIAAAbIAFACIAGABQADAAADgCQADgBACgDQAFgFAAgKIgBgJQgBgDgCgDQgBgDgDgBQgDgBgDAAIgFAAg");
	this.shape_10.setTransform(138.4,21.1);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgDAnIAAhFIgZAAIAAgIIA5AAIAAAIIgYAAIAABFg");
	this.shape_11.setTransform(132.2,19);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgVAAIARgYIAGAFIgKAQIgGADIAGAFIAKAPIgFAFgAgBAAIAQgYIAGAFIgKAQIgGADIAGAFIALAPIgGAFg");
	this.shape_12.setTransform(126.6,20);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgNAlQgGgDgDgFQgFgFgCgIIgBgQQAAgJABgHQADgHAEgGQAIgKAOAAQAIAAAGADQAGADAEAFQAEAFACAIQACAHAAAIQAAAJgCAIQgDAIgDAFQgEAFgGADQgHACgHAAQgHAAgGgDgAgIgdQgEACgDAEQgFAIAAAPIAAAMQACAGACAEQADAEAEADQAFADAEgBQAFAAAEgBQAEgCADgEQAGgIAAgQIgBgLQgCgGgDgEQgCgFgEgCIgEgCIgGgBQgEABgEABg");
	this.shape_13.setTransform(117.3,19);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AAWAnIgIgWIgcAAIgHAWIgJAAIAdhNIADAAIAdBNgAALAJIgJgVIgCgNIgCANIgJAVIAWAAg");
	this.shape_14.setTransform(110.3,19);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AAKAcIgRgaIgEAAIAAAaIgJAAIAAg2IAJAAIAAAZIAEgCIAQgXIAKAAIgRAVIgEAEIAFADIATAag");
	this.shape_15.setTransform(102,20.1);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AANAcIAAggIAAgHIgEAHIgYAgIgGAAIAAg2IAJAAIAAAgIAAAGIAAAAIAFgHIAXgfIAFAAIAAA2g");
	this.shape_16.setTransform(96,20.1);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AAeAjIgCgPIg/AAIAAg2IAJAAIAAAvIASAAIAAgvIAIAAIAAAvIATAAIAAgvIAJAAIAAAvIAIAAIAAAWg");
	this.shape_17.setTransform(89.2,20.8);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AANAnIAAghIAAgGIgFAGIgYAhIgEAAIAAg2IAJAAIAAAgIgBAGIABAAIADgHIAYgfIAGAAIAAA2gAgEgXIgFgCIgEgFQgCgCgBgDIAIgDQABAGADABQACACADAAQADAAADgCQADgCABgFIAGADQgBAGgEAEQgFADgGgBIgFAAg");
	this.shape_18.setTransform(81.7,19);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgKAbQgEgCgDgEIgFgJQgBgGAAgGQAAgGABgGQACgEADgFQAHgHAKAAQAGAAAFACQAEACADAEQADAEABAFQACAFAAAGQAAAHgCAFQgBAGgDADQgGAIgMAAQgFAAgFgCgAgOAAIABAIQABAEABACQACAEADABQADACADAAQAIAAADgFQAEgFAAgLIgBgHQAAgEgDgDIgEgEQgDgCgEAAQgOAAAAAUg");
	this.shape_19.setTransform(75.8,20.1);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgWAnIAAhMIAGAAIACAHIAAAAQADgEAEgCQAEgCAEAAQALAAAFAGQADAEACAFIABANQAAAHgCAEQgCAGgDAEQgDADgFACQgFADgEAAIgHgBIgFgCIAAAXgAgFgeIgDADQgEACgBAGIAAAbIAFACIAGABQADAAADgCQADgBACgDQAFgFAAgKIgBgJQgBgDgCgDQgBgDgDgBQgDgBgDAAIgFAAg");
	this.shape_20.setTransform(70,21.1);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AgEAcIAAgvIgQAAIAAgHIApAAIAAAHIgRAAIAAAvg");
	this.shape_21.setTransform(64.8,20.1);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AgHAbQgEgCgDgEIgEgJIgBgMQAAgGABgGQACgEADgFQAGgHALAAIAIABIAHACIgCAIIgGgCIgHgBQgOAAAAAUIABAIQAAAEACACIAFAFQADACAEAAIAHgBIAFgDIADAHQgDACgFACQgEABgFAAQgFAAgFgCg");
	this.shape_22.setTransform(60.2,20.1);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AgLAcIgFgEIgDgFIgCgGQABgFACgEQACgDADgBQAEgBAEgBIAKgBIAEAAIACAAIABgGIgBgFIgBgDIgEgCIgFAAIgEAAIgEABIgEABIgEABIgCgHQAEgCAGgBQAFgBAFAAQAFAAAEABQAEABACADIACAGIAAAGIAAALIAAAMIAAAIIABAHIgGAAIgDgIIAAAAIgCADIgEADIgFACIgFAAIgHAAgAAAADIgGABIgEAEQAAAAgBAAQAAABAAAAQAAABAAABQgBAAAAABQAAADADADQADADAEgBIAEAAIAFgCIADgDIABgDIAAgJIgCgBIgEAAg");
	this.shape_23.setTransform(54.8,20.1);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AgQAnIgHgCIACgIIAHACIALAAIAGAAIAGgDIAEgFQABgDAAgEQAAgGgEgEQgFgDgHAAIgDgBIgCAAIgGAAIAAgHIACAAIACAAIADAAIADAAIACAAIAFgBIAEgEIADgDIABgFQAAgDgBgDIgDgEIgFgCIgFgBIgLABIgGACIgDgHIAIgDQAGgBAHAAIAIABIAHADQAEADACADQACADAAAGQAAAFgEAFQgDAGgIACIAAAAQAIABAFAEQAEAFAAAHIgBAGIgBAGQgDAEgEADQgEADgFACQgFABgFAAIgMgBg");
	this.shape_24.setTransform(49.1,19);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AgLAbIgGgEQgCgCgBgFQgBgEAAgHIAAggIAJAAIAAAeIAAAIIACAFIADADIAFABIAFgBIAEgCIADgEIACgFIAAgjIAJAAIAAAmIAAAIIABAIIgGAAIgCgJIgBAAQgCAEgEADQgFADgFAAIgIgBg");
	this.shape_25.setTransform(232.7,9.2);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AgNAcIAAg2IAGAAIACAGIAFgFQACgCAFAAIAHABIgCAJIgGgCQgFAAgCADQgDACAAAEIAAAmg");
	this.shape_26.setTransform(228.3,9.1);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AgEAFQAAgBAAAAQgBgBAAAAQAAgBAAgBQAAAAAAgBQAAAAAAAAQAAgBAAgBQAAAAABgBQAAAAAAAAQABgBAAAAQABgBAAAAQABAAABAAQAAgBAAAAQADABACACQAAAAAAAAQABABAAAAQAAABAAABQAAAAAAAAQAAABAAAAQAAABAAABQAAAAgBABQAAAAAAABQgCACgDAAQAAAAAAgBQgBAAgBAAQAAAAgBgBQAAAAgBAAg");
	this.shape_27.setTransform(224.9,11.4);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AAKAmIgRgZIgEAAIAAAZIgJAAIAAhLIAJAAIAAAuIAEgCIAQgXIAKAAIgRAWIgDADIAEAEIASAZg");
	this.shape_28.setTransform(221.5,8.1);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("AgKAbIgIgCIADgIIAGADIAJABQAEAAADgCIACgCIAAgEQAAgEgCgCIgEgDIgFgCIgHgCIgFgFQgCgCAAgFQAAgFABgCQACgDACgCQAEgEAHAAIAKABIAHACIgCAIIgGgCIgIgBQgEAAgCABQgCACAAAFQAAAAAAABQAAAAABABQAAAAAAABQABAAAAAAIAFADIAFADIAGADIAGAEQABADAAAFIgBAHIgDAFQgCADgFAAQgDACgEAAQgGAAgEgCg");
	this.shape_29.setTransform(216.2,9.2);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FFFFFF").s().p("AANAcIAAgeIgBgIIgBgFQgDgEgGAAIgFAAIgEADQgEADgBAFIAAAkIgJAAIAAg2IAGAAIACAHQADgEAEgCQAFgCAFAAIAIABQAEABACADQACACABAFIABALIAAAgg");
	this.shape_30.setTransform(210.9,9.1);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#FFFFFF").s().p("AgMAEIAAgHIAZAAIAAAHg");
	this.shape_31.setTransform(205.9,8.7);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#FFFFFF").s().p("AgLAbIgFgDIgEgFIgBgGQAAgFACgDQACgEAEgBQAEgCAFAAIAJgBIADAAIAEAAIAAgGIgBgFIgCgEIgDgBIgGAAIgDAAIgEAAIgEABIgDACIgEgGQAFgDAFgBQAGgBAFgBQAGABADABQADACACACIADAFIABAHIgBALIAAANIAAAHIACAGIgHAAIgCgHIgBAAIgDADIgDACIgFACIgFABIgHgBgAgBADIgFACIgEACQAAABgBAAQAAABAAAAQAAABAAABQAAAAAAABQAAADACADQADACAEAAIAFAAIAEgCIADgDIACgDIAAgJIgEgBIgDAAg");
	this.shape_32.setTransform(201.1,9.2);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#FFFFFF").s().p("AALAmIgRgZIgGAAIAAAZIgJAAIAAhLIAJAAIAAAuIAFgCIAQgXIAKAAIgRAWIgEADIAFAEIATAZg");
	this.shape_33.setTransform(196.2,8.1);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#FFFFFF").s().p("AAAAcIgYg3IAJAAIAOAfIACAKIACgKIANgfIAKAAIgYA3g");
	this.shape_34.setTransform(190.6,9.2);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#FFFFFF").s().p("AgKAbQgFgCgDgEIgDgJQgCgFAAgHQAAgGACgFQABgGADgDQAGgIALAAQAGAAAEACQAFACADAEQADAEACAFQABAGAAAFQAAAHgBAGQgCAEgDAFQgHAHgLAAQgFAAgFgCgAgOAAIABAIQABAEACADQABACADACQADACADAAQAIAAADgFQAEgGAAgKIgBgHQgBgEgCgDIgEgFQgDgBgEAAQgOAAAAAUg");
	this.shape_35.setTransform(185,9.2);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#FFFFFF").s().p("AAKAmIgRgZIgEAAIAAAZIgJAAIAAhLIAJAAIAAAuIAEgCIAQgXIAKAAIgRAWIgDADIAEAEIATAZg");
	this.shape_36.setTransform(179.8,8.1);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#FFFFFF").s().p("AgLAbIgGgEQgCgCgBgFQgBgEAAgHIAAggIAJAAIAAAeIAAAIIACAFIADADIAFABIAFgBIAEgCIADgEIACgFIAAgjIAJAAIAAAmIAAAIIABAIIgGAAIgCgJIgBAAQgCAEgEADQgFADgFAAIgIgBg");
	this.shape_37.setTransform(173.9,9.2);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#FFFFFF").s().p("AANAmIAAgfIAAgHIgCgFIgEgDIgFgBQgEAAgFADIgEAEIgBAEIAAAkIgJAAIAAhLIAJAAIAAAcQADgEAEgCQAEgCAFAAIAIABQADACADACQACACABAFIABALIAAAgg");
	this.shape_38.setTransform(168,8.1);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#FFFFFF").s().p("AgTAbIAAgHIAZgiIAEgFIgdAAIAAgIIAnAAIAAAIIgZAjIgEAEIAdAAIAAAHg");
	this.shape_39.setTransform(162.4,9.2);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#FFFFFF").s().p("AgEAFQAAgBAAAAQgBgBAAAAQAAgBAAgBQAAAAAAgBQAAAAAAAAQAAgBAAgBQAAAAABgBQAAAAAAAAQABgBAAAAQABgBAAAAQABAAABAAQAAgBAAAAQADABACACQAAAAAAAAQABABAAAAQAAABAAABQAAAAAAAAQAAABAAAAQAAABAAABQAAAAgBABQAAAAAAABQgCACgDAAQAAAAAAgBQgBAAgBAAQAAAAgBgBQAAAAgBAAg");
	this.shape_40.setTransform(158.8,11.4);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#FFFFFF").s().p("AARAcIgPgjIgCgJIgCAJIgNAjIgFAAIgTg3IAKAAIALAfIACAKIAAAAIACgKIAMgfIAFAAIAOAfIACAKIACgKIAKgfIAIAAIgSA3g");
	this.shape_41.setTransform(153.7,9.2);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#FFFFFF").s().p("AAQAcIgNgjIgDgJIgCAJIgNAjIgEAAIgTg3IAJAAIALAfIABAKIABAAIADgKIALgfIAGAAIAMAfIADAKIADgKIAJgfIAJAAIgTA3g");
	this.shape_42.setTransform(145.6,9.2);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#FFFFFF").s().p("AARAcIgPgjIgCgJIgBAJIgOAjIgEAAIgUg3IAKAAIALAfIACAKIAAAAIACgKIAMgfIAFAAIAOAfIACAKIACgKIAKgfIAIAAIgSA3g");
	this.shape_43.setTransform(137.6,9.2);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("#FFFFFF").s().p("AgLAbIgFgDIgDgFIgBgGQAAgFACgDQACgEADgBQADgCAFAAIALgBIADAAIACAAIABgGIgBgFIgCgEIgDgBIgFAAIgDAAIgFAAIgEABIgEACIgCgGQAEgDAGgBQAFgBAFgBQAGABADABQAEACACACIACAFIAAAHIAAALIAAANIAAAHIABAGIgGAAIgDgHIAAAAIgDADIgDACIgFACIgFABIgHgBgAAAADIgGACIgEACQAAABgBAAQAAABAAAAQAAABAAABQAAAAAAABQAAADACADQADACAEAAIAEAAIAFgCIADgDIABgDIAAgJIgCgBIgDAAg");
	this.shape_44.setTransform(127.8,9.2);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.f("#FFFFFF").s().p("AAMAbIAAgYIgXAAIAAAYIgJAAIAAg2IAJAAIAAAYIAXAAIAAgYIAJAAIAAA2g");
	this.shape_45.setTransform(122.2,9.2);

	this.shape_46 = new cjs.Shape();
	this.shape_46.graphics.f("#FFFFFF").s().p("AANAbIAAgfIAAgHIgEAHIgZAfIgEAAIAAg2IAJAAIAAAhIgBAHIABAAIAEgHIAYghIAEAAIAAA2g");
	this.shape_46.setTransform(113.4,9.2);

	this.shape_47 = new cjs.Shape();
	this.shape_47.graphics.f("#FFFFFF").s().p("AANAbIAAgfIAAgHIgFAHIgYAfIgEAAIAAg2IAJAAIAAAhIgBAHIABAAIADgHIAYghIAGAAIAAA2g");
	this.shape_47.setTransform(107.4,9.2);

	this.shape_48 = new cjs.Shape();
	this.shape_48.graphics.f("#FFFFFF").s().p("AATAjIgCgPIgpAAIAAg2IAJAAIAAAvIAXAAIAAgvIAJAAIAAAvIAIAAIAAAWg");
	this.shape_48.setTransform(101.7,9.9);

	this.shape_49 = new cjs.Shape();
	this.shape_49.graphics.f("#FFFFFF").s().p("AgLAbIgFgDIgEgFIgBgGQAAgFACgDQADgEADgBQAEgCAEAAIAKgBIAEAAIADAAIAAgGIgBgFIgBgEIgEgBIgFAAIgEAAIgEAAIgEABIgDACIgDgGQAEgDAGgBQAFgBAFgBQAGABADABQADACADACIACAFIABAHIgBALIAAANIAAAHIACAGIgHAAIgCgHIgBAAIgCADIgEACIgFACIgFABIgHgBgAgBADIgFACIgEACQAAABgBAAQAAABAAAAQAAABAAABQgBAAAAABQABADACADQADACAEAAIAFAAIAEgCIADgDIACgDIAAgJIgDgBIgEAAg");
	this.shape_49.setTransform(95.5,9.2);

	this.shape_50 = new cjs.Shape();
	this.shape_50.graphics.f("#FFFFFF").s().p("AgWAnIAAhMIAGAAIACAHIAAAAQADgEAEgCQAEgCAEAAQALAAAFAGQADAEACAFIABANQAAAHgCAEQgCAGgDAEQgDADgFACQgFADgEAAIgHgBIgFgCIAAAXgAgFgeIgDADQgEACgBAGIAAAbIAFACIAGABQADAAADgCQADgBACgDQAFgFAAgKIgBgJQgBgDgCgDQgBgDgDgBQgDgBgDAAIgFAAg");
	this.shape_50.setTransform(90.1,10.2);

	this.shape_51 = new cjs.Shape();
	this.shape_51.graphics.f("#FFFFFF").s().p("AgLAbIgFgDIgDgFIgBgGQAAgFACgDQACgEADgBQADgCAFAAIALgBIADAAIACAAIABgGIgBgFIgCgEIgDgBIgFAAIgDAAIgFAAIgEABIgEACIgCgGQAEgDAGgBQAFgBAFgBQAGABADABQAEACACACIACAFIAAAHIAAALIAAANIAAAHIABAGIgGAAIgDgHIAAAAIgDADIgDACIgFACIgFABIgHgBgAAAADIgGACIgEACQAAABgBAAQAAABAAAAQAAABAAABQAAAAAAABQAAADACADQADACAEAAIAEAAIAFgCIADgDIABgDIAAgJIgCgBIgDAAg");
	this.shape_51.setTransform(84.1,9.2);

	this.shape_52 = new cjs.Shape();
	this.shape_52.graphics.f("#FFFFFF").s().p("AgUAbIgDAAIACgIIACABQABAAAAAAQABAAABgBQAAAAAAAAQABgBAAAAQACgCABgFIADgOIABgYIAgAAIAAA2IgJAAIAAguIgPAAIgBAKIgBAKIgCAKIgCAIQgCAEgDACQgCADgDAAg");
	this.shape_52.setTransform(78.3,9.2);

	this.shape_53 = new cjs.Shape();
	this.shape_53.graphics.f("#FFFFFF").s().p("AAKAbIgRgZIgEAAIAAAZIgJAAIAAg2IAJAAIAAAaIAEgCIAQgYIAKAAIgRAXIgDADIAEADIASAZg");
	this.shape_53.setTransform(73.8,9.2);

	this.shape_54 = new cjs.Shape();
	this.shape_54.graphics.f("#FFFFFF").s().p("AgIAbQgFgCgDgEIgEgJQgBgFAAgHQAAgNAFgHQAEgEAEgCQAEgCAFAAIAIABIAHADIAEAGQACAFABAHIgBAHIgiAAIABAIIACAHQADADADABIAHABIAHgBIAHgDIACAGIgIAEQgEACgHAAQgEAAgFgCgAAOgFQAAgJgEgDQgCgDgHAAIgEABQgDAAgCACQgDADgBAJIAaAAIAAAAg");
	this.shape_54.setTransform(68,9.2);

	this.shape_55 = new cjs.Shape();
	this.shape_55.graphics.f("#FFFFFF").s().p("AAWAjIgBgPIgpAAIgBAPIgGAAIAAgWIAGAAIADgEIACgJIADgOIABgUIAgAAIAAAvIAIAAIAAAWgAgFgQIgBALIgDAJIgDAJIAYAAIAAgnIgQAAg");
	this.shape_55.setTransform(62.1,9.9);

	this.shape_56 = new cjs.Shape();
	this.shape_56.graphics.f("#FFFFFF").s().p("AgIAbQgFgCgDgEIgEgJQgBgFAAgHQAAgNAFgHQAEgEAEgCQAEgCAFAAIAIABIAHADIAEAGQACAFABAHIgBAHIgiAAIABAIIACAHQADADADABIAHABIAHgBIAGgDIADAGIgIAEQgEACgHAAQgEAAgFgCgAAOgFQAAgJgEgDQgCgDgHAAIgEABQgDAAgCACQgDADgBAJIAaAAIAAAAg");
	this.shape_56.setTransform(53.6,9.2);

	this.shape_57 = new cjs.Shape();
	this.shape_57.graphics.f("#FFFFFF").s().p("AgbAbIAAg2IAJAAIAAAVIAFAAIAFgBQAFAAADACIAGADQADACAAACIABAHQAAAFgBAEQgBADgDACQgDADgDABIgLABgAgSABIAAATIAIAAIAGAAIAEgCQABgDAAgFQAAgFgBgCQgDgDgHAAIgEAAgAATAbIAAg2IAJAAIAAA2g");
	this.shape_57.setTransform(47.2,9.2);

	this.shape_58 = new cjs.Shape();
	this.shape_58.graphics.f("#FFFFFF").s().p("AAMAbIAAgYIgXAAIAAAYIgJAAIAAg2IAJAAIAAAYIAXAAIAAgYIAJAAIAAA2g");
	this.shape_58.setTransform(40.6,9.2);

	this.shape_59 = new cjs.Shape();
	this.shape_59.graphics.f("#FFFFFF").s().p("AgEAbIAAguIgQAAIAAgIIApAAIAAAIIgRAAIAAAug");
	this.shape_59.setTransform(35.5,9.2);

	this.shape_60 = new cjs.Shape();
	this.shape_60.graphics.f("#FFFFFF").s().p("AALAbIgRgZIgGAAIAAAZIgJAAIAAg2IAJAAIAAAaIAFgCIARgYIAJAAIgRAXIgEADIAFADIATAZg");
	this.shape_60.setTransform(31.1,9.2);

	this.shape_61 = new cjs.Shape();
	this.shape_61.graphics.f("#FFFFFF").s().p("AgIAbQgFgCgDgEIgEgJQgBgFgBgHQAAgNAHgHQADgEAFgCQADgCAGAAIAHABIAHADIAFAGQABAFAAAHIAAAHIgjAAIABAIIAEAHQABADAEABIAHABIAIgBIAGgDIADAGIgJAEQgEACgGAAQgGAAgEgCgAAOgFQAAgJgDgDQgDgDgGAAIgFABQgDAAgBACQgFADgBAJIAbAAIAAAAg");
	this.shape_61.setTransform(25.3,9.2);

	this.shape_62 = new cjs.Shape();
	this.shape_62.graphics.f("#FFFFFF").s().p("AgKAbQgFgCgDgEIgDgJQgCgFAAgHQAAgGACgFQABgGADgDQAGgIALAAQAGAAAEACQAGACACAEQADAEACAFQABAGAAAFQAAAHgBAGQgCAEgDAFQgHAHgLAAQgFAAgFgCgAgOAAIABAIQAAAEACADQACACADACQADACADAAQAHAAAEgFQAEgGAAgKIgBgHQgBgEgBgDIgFgFQgDgBgEAAQgOAAAAAUg");
	this.shape_62.setTransform(19.6,9.2);

	this.shape_63 = new cjs.Shape();
	this.shape_63.graphics.f("#FFFFFF").s().p("AgWAnIAAhMIAGAAIACAHIAAAAQADgEAEgCQAEgCAEAAQALAAAFAGQADAEACAFIABANQAAAHgCAEQgCAGgDAEQgDADgFACQgFADgEAAIgHgBIgFgCIAAAXgAgFgeIgDADQgEACgBAGIAAAbIAFACIAGABQADAAADgCQADgBACgDQAFgFAAgKIgBgJQgBgDgCgDQgBgDgDgBQgDgBgDAAIgFAAg");
	this.shape_63.setTransform(13.8,10.2);

	this.shape_64 = new cjs.Shape();
	this.shape_64.graphics.f("#FFFFFF").s().p("AASAmIAAhDIgjAAIAABDIgJAAIAAhLIA1AAIAABLg");
	this.shape_64.setTransform(7.1,8.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_64},{t:this.shape_63},{t:this.shape_62},{t:this.shape_61},{t:this.shape_60},{t:this.shape_59},{t:this.shape_58},{t:this.shape_57},{t:this.shape_56},{t:this.shape_55},{t:this.shape_54},{t:this.shape_53},{t:this.shape_52},{t:this.shape_51},{t:this.shape_50},{t:this.shape_49},{t:this.shape_48},{t:this.shape_47},{t:this.shape_46},{t:this.shape_45},{t:this.shape_44},{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol15, new cjs.Rectangle(0,0,239.2,27.9), null);


(lib.Symbol14 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#720707").s().p("AurGBIAAsBIdXAAIAAMBg");
	this.shape.setTransform(94,38.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol14, new cjs.Rectangle(0,0,188,77), null);


(lib.Symbol12 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib._3rear2();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol12, new cjs.Rectangle(0,0,360,150), null);


(lib.Symbol11 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("EgnuAOGIAAzIICVAAIAAkvIBJgJIgSiZIAXgUIIZgqIAjAMIAKCgIF1AjIAAAZIgUAAIAJE4MAsDgAHIAohBIgVgbIhAAPIAtgsIgcgiIBBAAIg0goIA3gdIg4gUIBWAFIAAgQIAggFIgBgnIBQABIgGgrIBMAbIAUgKIghgjIg1ghIBAAaIAIgiIARAAIAAgZIgnglIAjASIAugCIAEgbIgUggIAlAXIgPgzIAcAiIAaARIAGgZIgMgMIAGgbIAaghIAZAZIgLAsIAAAmIAtgaIAGAwIAcANIAVgIIgFg2IAVgDIgDhXIAjAMIAAAmIAUApIAKhCIAhBDIAmg+IAUAvIAFBJIBzAbIgFGSIEnAAIAATIg");
	mask.setTransform(245.6,91.2);

	// Layer 1
	this.instance = new lib._2front();
	this.instance.parent = this;

	var maskedShapeInstanceList = [this.instance];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol11, new cjs.Rectangle(0,1,460,166.1), null);


(lib.Symbol10 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("Egj4AXNIAF/uIA0gtIAAhOQBFg1AnBUIAABDIAbAtIAXAZQBHA2gLAkQAngDgdCPQBEgBA7A2IgLAdIgiASIAAAbIAfAtIAvASISNAAIMXgZQF5qdkDrGMAgaAAoMAAAAtxg");
	mask.setTransform(230.2,144);

	// Layer 1
	this.instance = new lib._3middle();
	this.instance.parent = this;

	var maskedShapeInstanceList = [this.instance];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol10, new cjs.Rectangle(0.5,0,459.5,292.5), null);


(lib.Symbol8 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 5
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#333333").ss(1,1,1).p("AKmkbIAADcAH5BGIAzgFIAxgGIAwgFAHFBMIA0gGAGTBSIAygGAFcBYIA3gGAE0EXIAAiyAFaDsQCYALCbgzAJdg3IAAByAIsg2IAAB3AH5grIAABxAHFgjIAABvAGTgfIAABxAEqgUIAABsAFcgUIAABjAD4gIIAABmAC8AAIAABpAqljBIAAEVABeAxIAABBAA7AiIAABXAARAaIAABkAgWAdIAABpAA7DuQgtg5giAiQgjAyBvAMIAFADAA7DuIAHhwAA4EcIAAgHIADgnAg1AJIAABBAhcgDIAABAAiIgUIAABlAivgmIAACzAjUgyIAADJAkGhGIAADlAkyhTIAAD3AlchiIAAEBAmJhuIAAEDAm/h9IAAEIAnliCIAAEFAoPiPIAAEGAo/igIAAD+Apti0IAAEZ");
	this.shape.setTransform(308.1,147.1);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// Layer 4
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#333333").ss(1,1,1).p("AJ5itICHA4AB2hpIIDhIIAAAEIAAEvADVBGQgagqAzggAGWAcQAEg+hKAPIjaAYIizAUQgJhSgwAKQgpAGgPBPIjuAgAJjAIQgchKg6AlQg+BKgDBpAiIBVIARgCIAqgFAh3BTIACAgAB2AFIAACtAB2hpIAABuAr/ASIN1h7AFICAQhvgJhhA2");
	this.shape_1.setTransform(310.1,158);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(1));

	// Layer 3
	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f().s("#333333").ss(1,1,1).p("AKlhvInoEhIjEg4IDhgbIHPkQAqohKIKhDE");
	this.shape_2.setTransform(308,136.7);

	this.timeline.addTween(cjs.Tween.get(this.shape_2).wait(1));

	// Layer 2 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("EgmlAfwMgAFghPMAlbgFaIM6C6IISgdIgBk+IBUAaIAAhaIC5gjIAAiGIAFgBIAAoHIAFAAIAAgXICKAAIACkJIgMgVIAAg5IgcgWIAAgoIgtgCIgChaIgrgzIAAhpIOOAAMAAAA/fg");
	mask.setTransform(247.5,199.7);

	// Layer 1
	this.instance = new lib._1front();
	this.instance.parent = this;

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f().s("#463D2A").ss(1,1,1).p("AVqjWIhLAMIABELARIifIAAD5AUfjKMgqHAGh");
	this.shape_3.setTransform(100.4,151.2);

	var maskedShapeInstanceList = [this.instance,this.shape_3];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_3},{t:this.instance}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol8, new cjs.Rectangle(0.1,0,492,403), null);


(lib.Symbol7 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib._1rearbg();
	this.instance.parent = this;
	this.instance.setTransform(27,0);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol7, new cjs.Rectangle(27,0,269,184), null);


(lib.Symbol6 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("A0fv4MAnvAAAIA6BGIkiBhIAABkIAPgDIAAAIIAZAUIASgHIAAAFIBAAAIAAAeIBxBDIgDCtIBJAjIgjA3IgWACIjnA8IBpDkIB+AuIAAC0IA+AZIACAmIgtAAIh/AqIiTAcIAAGZMgkAAFFg");
	mask.setTransform(122.3,93);

	// Layer 1
	this.instance = new lib._1left();
	this.instance.parent = this;

	var maskedShapeInstanceList = [this.instance];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol6, new cjs.Rectangle(0,0,253,191), null);


(lib.Symbol4 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("ATpMAQj0AhlpgcQjPAyi8huQikhPAshgQgMhwBrh2MgnmAAtIAA0YQBBhCBBAGQB1BFCjEoIAUAAIBpgyIBpAAIBVAtIAoAgQBYAVg/CGQhgBKAQC9IAAA8IBkBLICbgKICgAAMAguAC4IAAgFIBBAAQEuhTLOgRQAdh8EAAUIAAOSQBGDIjlAAQj9AApqj1g");
	mask.setTransform(229.8,104.7);

	// Layer 1
	this.instance = new lib._3grass2();
	this.instance.parent = this;

	var maskedShapeInstanceList = [this.instance];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol4, new cjs.Rectangle(0,3.4,458,197.6), null);


(lib.Symbol3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("ArrUxMAAAgpjIXcAAMAAAAm0IlFAAImVBQIi5AAIpNBhg");
	mask.setTransform(99.7,119.5);

	// Layer 1
	this.instance = new lib._3right();
	this.instance.parent = this;

	var maskedShapeInstanceList = [this.instance];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol3, new cjs.Rectangle(24.5,0,129.6,252.6), null);


(lib.Symbol2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("A52PvMAAAgjXMAztAAAMgAFAnRg");
	mask.setTransform(164.5,124.2);

	// Layer 1
	this.instance = new lib._2upleft();
	this.instance.parent = this;

	var maskedShapeInstanceList = [this.instance];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol2, new cjs.Rectangle(0,0,329,250), null);


(lib.leafs = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#5DBE6D").s().p("AhJCZQgJgEgHgHQgGgGgFgKIgFgOQgtgSghguIgZgqQAAgOARgDQARgCAKATQAMgEAJgBQANgBAOAEQAOAEAKAHQALAIAHALIABABQACAEgEACQgKAGgPABQgOABgMgDQgMgEgMgIIgBAAQAMATAVAOQATAPAWAGQAaAIAhgKQAdgIARgRQAMgLgMgaQgKgTgNgKQgHAEgKAAQgVgCgLgdQgMgfAVgbQAVgaAeAFQAaAEAMATQAJAPgDATQgDAUgNAHQgMANAOAXQAKAQAJgCQAIgCAKgSQANgVAEgMQAGgTgJgLIgBgBQgHgEgFgIQgMgUATgeQAVgiAmAAQAlAAAOAgQANAbgKAYQgGARgSALQgSAMgOgFQgUAEgQAlIgFAMIAIgEQAMgFAPgBQAOgBAOAFQAGACgCAEIgBABQgHAPgJAIQgKAKgNAGQgNAGgOAAQgQABgMgFIAAABIgBgBIgTAUQgYAWgVAKQgdAPgjgBIgQgBQAGAGADAIQAFAKAAAIIAAABQAAABAAABQAAAAgBABQAAAAgBABQAAAAgBAAQgKgBgIgEg");
	this.shape.setTransform(72.5,15.8);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#5DBE6D").s().p("AhAA0IgBAAQgIgCACgIQAGgWANgTQAOgSASgMQAUgOAUgFQAWgFAXACIABAAQAIADgCAHQgGAWgNATQgOASgSAMQgTANgVAGQgPAEgQAAIgOgBg");
	this.shape_1.setTransform(161,30.6);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FCBE00").s().p("AggAdQgSgVAKgXQAIgUASgHQAOgGAQAHQARAHAAANQAAAJAHANQAHAMgDAKQgFARgZAFIgLABQgUAAgPgRg");
	this.shape_2.setTransform(91.4,110.7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FCBE00").s().p("AgTAOQgIgNAHgNQAGgMAKAAQAEAAAGAFQAGAGAEABQAHACABAKQABAJgFAGQgGAIgMACIgCAAQgMAAgHgLg");
	this.shape_3.setTransform(195.1,62.8);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FCBE00").s().p("AgBAdQgTgBgQgIQgQgHgNgNIgBAAQgEgEAFgFQAPgLASgFQASgFAQACQATABAQAIQAQAHANAMIABABQAEAFgFAEIAAAAQgPALgSAFQgOAEgNAAIgHgBg");
	this.shape_4.setTransform(196.6,70.5);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#5DBE6D").s().p("AhnA4QgDgGAEgGIAYggQAfgkAmgTQA6gcA2AWQAIAEgSAZQgUAagfAPQgdANgkACQgjgBgJACQgKACgKAJIgKALIgCABQgCAAgCgEg");
	this.shape_5.setTransform(176.2,72.8);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#5DBE6D").s().p("AAQBEQgPgIgMgRQgMgQgGgRQgGgTACgSQABgVAHgQIAAgCQACgCADgBQADAAACABQAQAKALAQQAMAOAGAUQAGATgCARQAAASgIATIgBABQgBACgDACIgBAAIgEgCg");
	this.shape_6.setTransform(203.9,95.6);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#5DBE6D").s().p("AgJAcQgRgHgOgLQgOgKgJgQIgBgBQgBgGAFgDQARgGASgBQASAAARAGQARAGAOAMQAOAKAJAQIAAABQADAGgGADQgSAGgRAAIgDABQgQAAgQgGg");
	this.shape_7.setTransform(188.9,90.4);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#5DBE6D").s().p("AAmBDQgWgDgTgLQgTgMgMgQQgMgTgEgTQgDgWAEgWIABgCQACgIAJABQAWADATALQATALAMASQAMAQAEAWQADAVgEAWIgBACQgCAHgHAAIgCAAg");
	this.shape_8.setTransform(193,119.1);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FCBE00").s().p("AgMAVQgMgIABgOQACgPAOgGQAMgGAIAFQAFAEAAAIQABAIADADQAFAGgGAJQgFAIgJACIgGABQgGAAgHgFg");
	this.shape_9.setTransform(159.4,117);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#5DBE6D").s().p("AARBCQgSgHgOgPQgNgNgGgSQgHgRACgTQACgUAJgRIABgCQAFgGAGADQASAIAOAOQAMANAIASQAFARgBATQgCATgJATIgBABQgDAEgEAAIgEgBg");
	this.shape_10.setTransform(143.4,176.1);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FCBE00").s().p("AgBAqQgYgBgKgWQgKgVAOgVQANgTAQACQAIABAHAKQAJALAHADQALAEAAAQQgBAQgKAKQgLALgSAAIgBAAg");
	this.shape_11.setTransform(158.6,155.1);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#5DBE6D").s().p("AhNAxIgIgGQgFgEgCgCIgBgDQgCgFADgMQAGgpA1gWQA2gYBBAOIACACQAEACACAFQACAFgCAEQgZA7g4AcQgbANgXAAQgWAAgSgNg");
	this.shape_12.setTransform(130.5,167.8);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#5DBE6D").s().p("AAFCEQgZgYgRghQgQgggEglQgEglAJghQAIghAUgfIACgCQAEgEAFgBQAFAAAEAEQAZAYARAhQAQAgAEAlQAEAhgJAlQgJAjgTAdIgCACQgEAEgFABQgFAAgEgEg");
	this.shape_13.setTransform(173.3,160.1);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#5DBE6D").s().p("AAVBEQgagJgagUQgXgTgQgaQgPgbgGgdIAAgDQAAgEADgEQADgDAFAAQAfgBAcAJQAdALAXATQAWASASAbQAPAaAGAeIAAADQAAAEgDAEQgDADgEAAIgGAAQgcAAgbgJg");
	this.shape_14.setTransform(154,167.5);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FCBE00").s().p("AgVA6QhKgCgVgtQgGgOAAgFIAAgCQABgGALgKQAiglBFAGQBGAGA5AwIABACQADAEgBAFQgCAGgEADQg9AqhEAAIgJgBg");
	this.shape_15.setTransform(154,141.6);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#5DBE6D").s().p("AgBBMIgCgBQgRgOgKgTQgKgUgBgUQAAgUAHgUQAIgUAQgQQAGgGAGAFIACABQARAPAKASQAJASACAWQABAUgIAUQgIAUgQAQQgDADgEAAQgDAAgCgCg");
	this.shape_16.setTransform(64.4,174.5);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FCBE00").s().p("AgfAYQgMgPADgQQACgOAMgKQANgKAKAHQAGAEAOAAQAMAAAGAHQALALgIAVQgIAXgYAFIgIABQgRAAgMgOg");
	this.shape_17.setTransform(46.9,154.9);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#5DBE6D").s().p("AAOCCIgCgCQgZgVgTggQgRgegGgjQgHgjAHgjQAGgiATgfQACgEAGgCQAFgBAEACIACADQAbAWARAeQASAgAGAjQAGAhgHAkQgGAigTAfIABAAQgDAFgFABIgDAAQgEAAgDgCg");
	this.shape_18.setTransform(37.2,167.6);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#5DBE6D").s().p("AhDBbQgEgDgBgEIAAgCQgCgeAJgdQAKgeARgWQATgYAYgRQAagQAdgGQAFAAADACQAEACABAFIAAACQACAdgJAeQgJAcgSAYQgSAYgZAQQgbARgcAFIgDABQgCAAgDgCg");
	this.shape_19.setTransform(54.1,163.9);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#5DBE6D").s().p("AheBHQgGgBgDgFQgEgEAAgFIABgDQAdhCA8gkQA6gjAtARQAOAGAEAEIABACQADAFAAAPQABAvhAAjQgwAbg5AAQgRAAgRgDg");
	this.shape_20.setTransform(45.3,142.2);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FCBE00").s().p("AgWA4Qg+gngWhIQgBgFADgFQACgGAFgCIADgCQBOgJA9AiQA7AhADAwQABAOgDAGIgBADQgDAEgQAJQgTALgWAAQgfAAgjgWg");
	this.shape_21.setTransform(71,148);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FCBE00").s().p("AgWAbQgPgMgBgPQgBgNAKgMQAKgMALAEQAGACAMgCQALgCAIAFQAMAIgDAVQgCAXgWAJQgIAEgHAAQgLAAgKgIg");
	this.shape_22.setTransform(42.9,77.4);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#5DBE6D").s().p("ABXBVQgDgIgEgGQgHgMgLgGIgugNQgmgMgagXQgdgYgNgiQgMgeAKgCQAXgDASADQAnAHAjAfQAkAfAWAuQALAYAEARQADAHgFAGQgCADgCAAQgBAAAAAAQAAAAgBAAQAAgBAAAAQAAAAgBgBg");
	this.shape_23.setTransform(24.8,68.7);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#5DBE6D").s().p("AgfAZQgSgFgOgLQgFgDAEgFIABgBQAOgNAOgFQAQgIASgBQAQgCASAFQAPAEAQALQAFAEgEAFIgBAAQgMAMgQAHQgPAIgTABIgGABQgNAAgOgEg");
	this.shape_24.setTransform(10.9,70.2);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#5DBE6D").s().p("AgZAiQgRAAgTgHQgGgDADgFIAAgCQAKgQAOgKQANgMASgGQARgGASAAQAUABAPAGQAGADgCAGIgBABQgJAPgOALQgNALgSAHQgQAGgQAAIgDAAg");
	this.shape_25.setTransform(19.7,91.3);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#5DBE6D").s().p("AgpBaQgDgCgCgDIAAgCQgHgYACgbQADgcALgVQALgYATgSQARgSAYgLQAEgCADABQAEACABADIABACQAHAbgCAYQgDAagLAXQgMAagSAQQgSATgYALIgDAAIgEAAg");
	this.shape_26.setTransform(5.2,97.2);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FCBE00").s().p("AgiAhQgvgkgFgzQAAgDADgDQAEgDAFAAQABAAAAgBQAAAAABAAQAAAAAAAAQABABAAAAQBHALAvAiQAvAhgIAfQgBAJgFADIgCACQgEACgPACIgOABQgoAAgnggg");
	this.shape_27.setTransform(61.2,115.8);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#5DBE6D").s().p("AhJAuQgdgIACgJQAOg3A5gRQAkgLAtAJQAXAEAPAHQAHACADAHQACAIgEgBIgOgDQgMgBgIAGQgGAEgUAZQgYAZgaAIQgPAEgQAAQgPAAgPgEg");
	this.shape_28.setTransform(15,124.9);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FCBE00").s().p("AhQA0IgCgBQgDgBgCgDQgBgEABgEQAKgZARgSQASgUAXgMQAWgNAbgDQAZgEAZAFIACABQAEABACAEQACADgCAEQgJAZgSASQgQATgYAOQgWAMgbAEIgUABQgPAAgRgDg");
	this.shape_29.setTransform(145.1,117.9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.leafs, new cjs.Rectangle(0,0,207.4,182.8), null);


(lib.border = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Bitmap1();
	this.instance.parent = this;
	this.instance.setTransform(-1.5,-1.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.border, new cjs.Rectangle(-1.5,-1.5,241,401), null);


(lib.blackup1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["rgba(0,0,0,0)","rgba(0,0,0,0.8)"],[0,1],1.2,-310,1.2,62.4).s().p("EgWVAwNMAAAhgZMAsrAAAMAAABgZg");
	this.shape.setTransform(143,308.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.blackup1, new cjs.Rectangle(0,0,286,617), null);


(lib.bird1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AACCPQg5gqgjg1QgMgRhCghQhIglhOgYQhagcgOgIQgUgNAVgXIAegaQAigaATAFQAdAHDfB+IA1gCQA7gBAlACQAeABAjAFQAWADAJgNQAZgfAsgVQBAgeAvAlIAbAUQAQAMANAEQALADAMABIAPABIgKAJQgWARgHAJQgIAMgBAJIgDAWQgIAnghAlQgZAdgeASQhAAphHAAQhHAAhOgpgAEKg9QgGAGAAAHQgBAIAFAGQAFAGAIAAQAIABAGgGQAGgFAAgIQABgIgGgFQgFgGgHgBIgCAAQgHAAgFAFg");
	this.shape.setTransform(43.3,18.4);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.bird1, new cjs.Rectangle(0,0,86.6,36.8), null);


(lib.bird = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AjHD0QhYgegjg4IgEgEQgLgKgnAEQgNABgBgBQgBgCAPgKQAOgJAMgUQAMgTADgSIAAAAQAOgxAxgXQA0gbBDAQQAJACAXALQAQgmA9hdQAthGAHg0QALABAQAVQARAYAMAhQAhBYgcBWQgTA5g0A0IgFAGQgEAEABABQAAABAAAAQABAAAAAAQABAAABAAQAAAAABAAQAXgKAcgUQAbgUAQgUQAigoAFg2QABgJACgDQACgEAKgIIABgBQBchJATgIQASgIAsAQQAWAIASAKQAxAdgUAMQgyAQgxATQhLAcg6BBIgyA8QggAngeAbQhXBShZAAQggAAgggKgAkjBPQgOACABAQQACARAPgBQAHAAAFgFQAFgGAAgGQAAgRgSAAIgDAAg");
	this.shape.setTransform(39.1,25.4);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.bird, new cjs.Rectangle(0,0,78.2,50.9), null);


(lib.tree1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_47 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(47).call(this.frame_47).wait(3));

	// Layer 3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#33FF00").s().p("AhGBuQgdguAAhAQAAg/AdgtQAeguAoAAQApAAAeAuQAdAtAAA/QAABAgdAuQgeAtgpAAQgoAAgegtg");
	this.shape.setTransform(-422.3,-197.3);

	this.timeline.addTween(cjs.Tween.get(this.shape).to({_off:true},48).wait(2));

	// Layer 6
	this.instance = new lib.tlogo1();
	this.instance.parent = this;
	this.instance.setTransform(114.2,401.9,1.18,1.18,0,0,0,77,26.2);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(30).to({_off:false},0).to({alpha:1},16).to({_off:true},2).wait(2));

	// Layer 5
	this.instance_1 = new lib.tlogo();
	this.instance_1.parent = this;
	this.instance_1.setTransform(120.9,308.6,1.32,1.32,0,0,0,131.1,24.6);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(24).to({_off:false},0).to({alpha:1},18).to({_off:true},6).wait(2));

	// bird1
	this.instance_2 = new lib.bird1();
	this.instance_2.parent = this;
	this.instance_2.setTransform(15.5,25.8,1,1,0,0,0,43.2,18.4);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(19).to({_off:false},0).to({x:77.5,y:52.8,alpha:1},8,cjs.Ease.get(1)).wait(2).to({scaleX:0.94,x:81.5},5).to({scaleX:1,x:77.5},2).to({_off:true},12).wait(2));

	// bird
	this.instance_3 = new lib.bird();
	this.instance_3.parent = this;
	this.instance_3.setTransform(174.5,-5.6,1,1,0,0,0,39.1,25.4);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(22).to({_off:false},0).to({x:145.2,y:16.9,alpha:1},8,cjs.Ease.get(1)).wait(2).to({regY:25.3,scaleX:0.86,rotation:-6,y:16.8},5).to({regY:25.4,scaleX:1,rotation:0,y:16.9},2).to({_off:true},9).wait(2));

	// Layer 8
	this.instance_4 = new lib.leafs();
	this.instance_4.parent = this;
	this.instance_4.setTransform(115.8,103.6,0.745,0.745,0,0,0,103.7,91.4);
	this.instance_4.alpha = 0;
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(7).to({_off:false},0).to({scaleX:1,scaleY:1,alpha:1},14,cjs.Ease.get(1)).to({_off:true},27).wait(2));

	// Layer 2 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	var mask_graphics_0 = new cjs.Graphics().p("ADlVVQhRhRAAhxQAAhyBRhRQBQhQBygBQByABBRBQQBQBRAAByQAABxhQBRQhRBRhygBQhyABhQhRg");
	var mask_graphics_1 = new cjs.Graphics().p("ACaUyQhjhjAAiMQAAiLBjhjQBjhjCLAAQCMAABjBjQBiBjAACLQAACMhiBjQhjBiiMAAQiLAAhjhig");
	var mask_graphics_2 = new cjs.Graphics().p("ABPUOQh0h0AAimQAAilB0h1QB1h1CmAAQClAAB1B1QB1B1AAClQAACmh1B0Qh1B1ilAAQimAAh1h1g");
	var mask_graphics_3 = new cjs.Graphics().p("AAFTrQiGiHAAi/QAAi/CGiHQCHiHC/AAQC/AACHCHQCHCHAAC/QAAC/iHCHQiHCHi/AAQi/AAiHiHg");
	var mask_graphics_4 = new cjs.Graphics().p("AhFTIQiZiZAAjZQAAjZCZiZQCYiZDZAAQDZAACZCZQCZCZAADZQAADZiZCZQiZCZjZAAQjZAAiYiZg");
	var mask_graphics_5 = new cjs.Graphics().p("AiQSlQirisAAjyQAAjzCrirQCqisDzAAQDzAACrCsQCrCrAADzQAADyirCsQirCrjzAAQjzAAiqirg");
	var mask_graphics_6 = new cjs.Graphics().p("AjbSBQi9i9AAkMQAAkNC9i9QC+i+ELAAQENAAC9C+QC+C9AAENQAAEMi+C9Qi9C+kNAAQkLAAi+i+g");
	var mask_graphics_7 = new cjs.Graphics().p("AklReQjQjPAAknQAAkmDQjPQDPjPElAAQEnAADPDPQDQDPAAEmQAAEnjQDPQjPDQknAAQklAAjPjQg");
	var mask_graphics_8 = new cjs.Graphics().p("AlwQ7QjijiAAlAQAAlADijgQDijiE/AAQE/AADiDiQDiDgAAFAQAAFAjiDiQjiDik/AAQk/AAjijig");
	var mask_graphics_9 = new cjs.Graphics().p("Am7QYQj0j0AAlaQAAlaD0jzQD0j0FZAAQFZAAD0D0QD0DzAAFaQAAFaj0D0Qj0D0lZAAQlZAAj0j0g");
	var mask_graphics_10 = new cjs.Graphics().p("AoGP0QkGkGAAlzQAAlzEGkGQEHkGFyAAQFzAAEGEGQEHEGAAFzQAAFzkHEGQkGEHlzAAQlyAAkHkHg");
	var mask_graphics_11 = new cjs.Graphics().p("ApQPRQkZkYAAmNQAAmMEZkZQEYkYGMAAQGNAAEZEYQEYEZAAGMQAAGNkYEYQkZEZmNAAQmMAAkYkZg");
	var mask_graphics_12 = new cjs.Graphics().p("AqbOuQkrkrAAmmQAAmmErkrQEqkqGmAAQGnAAErEqQEqErAAGmQAAGmkqErQkrErmnAAQmmAAkqkrg");
	var mask_graphics_13 = new cjs.Graphics().p("ArmOLQk9k9AAnBQAAm/E9k9QE9k9G/AAQHBAAE9E9QE8E9AAG/QAAHBk8E9Qk9E8nBAAQm/AAk9k8g");
	var mask_graphics_14 = new cjs.Graphics().p("AsoNnQlPlOAAnbQAAnZFPlPQFPlPHZAAQHaAAFPFPQFPFPAAHZQAAHblPFOQlPFPnaAAQnZAAlPlPg");
	var mask_graphics_15 = new cjs.Graphics().p("AtUNVQlhlhAAn0QAAnzFhlhQFhlhHzAAQH0AAFhFhQFhFhAAHzQAAH0lhFhQlhFhn0AAQnzAAlhlhg");

	this.timeline.addTween(cjs.Tween.get(mask).to({graphics:mask_graphics_0,x:69.8,y:144.6}).wait(1).to({graphics:mask_graphics_1,x:72.9,y:142.8}).wait(1).to({graphics:mask_graphics_2,x:76.1,y:141.1}).wait(1).to({graphics:mask_graphics_3,x:79.2,y:139.4}).wait(1).to({graphics:mask_graphics_4,x:82.3,y:137.7}).wait(1).to({graphics:mask_graphics_5,x:85.4,y:136}).wait(1).to({graphics:mask_graphics_6,x:88.6,y:134.3}).wait(1).to({graphics:mask_graphics_7,x:91.7,y:132.6}).wait(1).to({graphics:mask_graphics_8,x:94.8,y:130.9}).wait(1).to({graphics:mask_graphics_9,x:97.9,y:129.2}).wait(1).to({graphics:mask_graphics_10,x:101.1,y:127.5}).wait(1).to({graphics:mask_graphics_11,x:104.2,y:125.8}).wait(1).to({graphics:mask_graphics_12,x:107.3,y:124.1}).wait(1).to({graphics:mask_graphics_13,x:110.4,y:122.3}).wait(1).to({graphics:mask_graphics_14,x:112.7,y:120.6}).wait(1).to({graphics:mask_graphics_15,x:112.8,y:117.5}).wait(35));

	// Layer 1
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AjbR5QisgiibhSQiWhRh6h5QifihhYjPQhbjXAAjsQAAjkBYjVQBBibBniAQAZgQAYAUIAGAGQAQATgMAVIgFAGQgaAigVAeIgGAMQgKARAWANQAKAGAgAMIA0ATQB9AtBxBXQAcAVAbAYQAbAYAFABIAnABQCKACBUAwQAQAJADAAQAGgBATgRQATgSAUgQIAWgPQAggXAigQIghgvIghAHQgsAJgqAEQg7AFg4gEQilgKhhg2QgqgYhAhAQghgjALgKQAKgJAwAoQBiBPCWATQBjAJBkgMQArgGArgJQA1gLA1gRIAMgEQAkgNAOgKIAPgMQAMgLAOgRQAPgRAIgSQAIgTgEgLQgIgIgBgQQgBgPAGgMQALgTAZgGQAegHATAYQAWAYgMAfQgKAcgTADQgIABgJgEQgMAAgJAMQgGAIgIASQgIARAQgBQBJgaAggKQARgFAEgKIANgjQATgpAhgcQAygsA5AJQAJABgKAcQgMAfgbAXQgYAVgkALQgiAJgIADQgHAEgFAFIgGAHQABABAFgBIAmgJIAggJQAZgGARgCQBCgJAfAMQAQAHAGAGQAFAFgDAEQgmAAgiAFQgSADgWAHIggAMQg2ASiGA4QhEAdgwATQgpAQgZAIIAbAmIAngLQAigJAogHIB1gUQCggcBWgvQBqg7BFh6IAkhCQAUghAOgPQAMgLAQAAQAQAAALALQCiCiBZDWQBYDVAADkQAADshbDXQhXDPihChQh6B6iYBRQibBTitAgQgrAJgbgGQghgHgUgcQgNgTgGgYQgFgQgDgeIgEgmQgJhVgBiQQgBhGAHhOIAShmQAMg9gIglQgHglgliEQgdhihRiMQhLh+gWgKQgSgIgWBBQgVA8AEAXQAEAiAkBcQAOAhAMAPQALAOAdAVQARANARAGQATAHAJgEQAJgJAOgCQAPgCAMAGQARAJAHAXQAIAcgVAUQgUAWgfgJQgbgHgEgTQgBgIACgIQAAgMgMgIQgHgFgSgHQgUgGALAfQAEARANAaQA7CeANDQQAICIgOCHQgGBBgQA9QgPA3gsANQgOAEgUAAQgaAAgjgHgADIIOQgQAHgOAOQgOAPgIATQgLApgGAwQgMBWAJCJQAJB0ALAhQAIAVAPAHQANAFAXgFQCfgfCQhOQCMhMBxhxQAUgTAageQAKgtgFhHQgFhFgghHQgjhTg5gvQhDg4hIgIQhXgIhsA2QhrA2g5BrQgFAJABAFQABAFAHgGIAhgcQAYgUANgEQAkgNAvAPQAxAQAoAnQAOANgDAJQgCAHgRAJQgkATgqADQgoADgfgNQgIgDgNgJQgNgHgHgDQgIgDgIAAQgJAAgKADgAo9EYQhQAIg7BEQg7BDgaBwQgUBSANBCQAHAlAUAlIAOAPQBnBnCABIQCABJCPAkQAtALANABQAjABAQgWQAQgXAKgxQAJgrAGhJQADgxAAgbQAChQgWgRQgMgJgNgEQgMgCgRAEQgZAHgGABQgjADghgNQgzgVgdgxQgIgMACgHQACgHAPgEQAtgMArAGQApAHAaAWQAEADAOATQALAOAKACQAHACAGgDQAHgDACgHQAJgRgOgpQgahJgug8QhIhchrgmQhFgYhIAAQgVAAgVACgAryE4QgdAJgsAXQg2AegZAbQgiAlgIAhQgIAbAJAcQAYArAcAqQAOAPAJgtQAShZAHgTQARg1AhgyQAdgqAUgNQABgBABAAQAAgBABAAQAAgBAAAAQAAAAgBgBIgBAAIgHABgAMGE5QASAQAaAsQAaAtARAsQAHATAGAeIANAxQAFAPADAFQAIAOAKgKQACgDAMgUIARgeQAOgYACgJQACgPgJgXQgTgwg3gzQgigegwgUQgWgJgHAAQgHAAANALgArIgVQhrAUhRBGQhhBWgbCcQgDAQACAMQABAKAGAQQAGATAEABQAEACAQgOIAvgsQAlggAjgXQAwgfBJgSQBLgUBUgCIATgBQAJgBAGgJQALgOgNgOQgVgZgtAJQggALgZAEQglAGgjgFQgygIgogdQgjgbAKgJQAZgUAWgJQAxgUBAAKQAzAIA9AhQA9AjAgAoQAXAdAUAKQALAFApALQBbAYBMA4QAzAlASAaQAMATgMgpQgMgqgggwQg0hQgngqQhIhLhmgxQhOgkhSAAQgkAAgkAHgAM7DzQBoAzAqA3QAhAqAKgSIARgwQADgkgRgwQgWhHg6hFQgzg9hQggQhUgghhAGQgwAEgNAIQgJAGgBAHQgBAIAIAFQAGAEARAAIAZgCQAkAAAfAMQAiAMAZAWQATAQARAYQAMARgDAHQgCAGgVAGQgZAHgaAAQgiABgigNQgfgLgcgXQgNgLgagcQgYgbgPgMQgNgJgKAAQgIAAgPAGQh2A1hVB/QgdAsgTArQgQAlACAJQABAGAQgLIA0gkQBphBCUgfQAwgKAvAAQBuAABsA1gAgGkfQgkAPgoAdQg5ApAXAUQAaAaA1BPQA7BZAmBQQAdA+AZBaQAOA4AFgOQALgnAbhIQAJgXABgQQABgKgDgbQgCgbgfhRQghhegkhDQgHgNgCgBQgFgDgMAEQgLADgGAIIgIAXQgEAPgSAHQgQAGgUgKQgWgLAAgbQAAgaAYgOQAVgMAOAJQADACAEAGQAEAEAEABQAGABAHgCQAHgCAEgDQAHgGgCgJQgBgFgGgKQgTgjgJgKQgHgIgHAAIgGABgAv4i6QgZADgRATQgKANgEArQgGA4gBA8QABAvADAoIACAWQACAPADAHQAHAQAbgkQAwg/AWgVQBfhbCEghQAwgMA0ADIAlACQgDgHgwgVQg9gbhEgQQhEgQhPgEIgrgBQgbAAgTACgAMkhJQBEAXA5ApQA6AoAlA2QAbAmAMgDQAKgCAEgdQACgoAAgpQAAgqgDgxQgDgfgCgKQgFgWgNgPQgRgVgXgFQg5gMicAYQhXANhHAoQgZAPgJALQgKAKAOgDQAegHAgAAQA8AABGAXgADFhhQALAgAaBgQADAIAFgLIAQglQARglAZgrQAbgsAYggIAYgbQALgMAAgBQgJgIgvAJQgxAJgwAWQgbAIgaAQQgWAOgOAPQgLANAGAAQADAAAQgGQAGgBAGAAQASAAAJARgAtHkCQBuAQB3A1QByAxBqBhQA0AuAdAfQgBgUggg0QgyhUhnhpQhfhghlg+IgZgOQg6ghhHgYIgPgGQgqgOgfAEQgdADgOATIgVAuQgPAmgMAjQAAAHgKAhQgIAkBTgIIAkgBQAnAAAtAGgANTnHQhMAYhuBNQh8BWhWBiQh8CNAAAtQAVgcA+gyQBUhDBmgzQCjhSDNgEQAsAAAPgOQAHgGAAgJQAAgEgDgMQgPgwgSgtIgRglQgFgLgFgGQgHgGgLgEQgKgDgNAAQgeAAgxAQgAmGjuQgEAHAQASQBBBSAXAwQADAIAGgSQAKgiALgXIAJgPQAGgIAJgCQAOgDAWANQAbAQgegeQgSgTgjgQQgmgUhBgIIgQgCQgNAAgCAGgAMBqSIgcAoQgmA3g/A3QhWBKhXAcQhOAYiDAXQh+AWgHADQgYAIgEAHQgHAIAJAQIAkBDQAFAJALgBQALgBAfgOQAegNA4gMQA0gLAmgDQAUgBAlACQAXACAGgHQAPgPBzhfQA9gxBjgyQA7gdA8gYQAbgKAEgVQADgSgPgXQgOgVgWgbQgaghgNgBIgBAAQgPAAgXAkgAKYtIIg7gtQgZgSglgUQgcgPAbgcQAcgbAdAJQAgATAZAUIA3AtQAMAKADAQQABAQgJAMQgKANgQACIgEAAQgNAAgLgJgArOtoQgIgMANgRQAJgOASgMIAVgPQCNhhClg1QBdgeBGgNQBTgQBWAAQA2AAAIAkQAEAOgJAMQgKAMgSABIg2AAQhQAAhBANQg0AKhXAcQhNAYhEAlIgnAWQgtAagyAkQgHAGgSAGQgVAHgQABIgIABQgYAAgJgNgACCwVQgEgDgXgJQgLgEADgMIAIgXQAGgVAAgZIAUAPQAXATAOAYQADAHgBAEQgPAfgOAAQgEAAgFgDg");
	this.shape_1.setTransform(115.7,115.2);

	var maskedShapeInstanceList = [this.shape_1];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.shape_1).to({_off:true},48).wait(2));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-432.3,-212.8,726.4,593.8);


(lib.Symbol16 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.Symbol14();
	this.instance.parent = this;
	this.instance.setTransform(94,38.5,1,1,0,0,0,94,38.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(60).to({alpha:0.551},5).to({alpha:1},5).wait(4));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,188,77);


(lib.Symbol13 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgIBJQgDgEgBgFQABgGADgDQADgDAFAAQAGAAADADQADADABAGQgBAFgDAEQgDADgGAAQgFAAgDgDgAgEAkIgEglIAAhKIARAAIAABKIgDAlg");
	this.shape.setTransform(145.3,-6.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgRA0QgJgEgFgHQgGgIgDgKQgDgKAAgNQAAgaAMgOQAGgIAJgDQAJgEAKAAQAIAAAHABQAHACAGAEQAGAFADAJQAEAHAAAOIgBAPIhEAAQAAAJACAIQACAHAEAFQAEAFAGADQAHACAIAAQAIAAAHgCQAHgDAEgEIAGANQgGAFgKADQgKADgKAAQgMAAgJgEgAAbgLQAAgQgGgGQgGgHgLAAQgGAAgFABIgJAGQgHAGgCAQIA0AAIAAAAg");
	this.shape_1.setTransform(136.2,-4.5);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("Ag9A1IAAhpIARAAIAABbIAkAAIAAhbIARAAIAABbIAkAAIAAhbIARAAIAABpg");
	this.shape_2.setTransform(123,-4.5);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AglA1IAAhqIARAAIAAApIAKgCIAJAAQAKAAAHADQAIACAFAEQAFAFACAEQACAGAAAHQAAATgMAJQgFAFgJACQgKACgLAAgAgUABIAAAlIAPABQAGAAAFgBQAFgCADgCQAGgFAAgKQAAgJgGgFQgGgFgMAAIgIAAg");
	this.shape_3.setTransform(110.7,-4.4);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgoA1IgFgBIACgPIAGABQAFABADgEQADgEADgKQACgKACgRIACgvIA/AAIAABqIgRAAIAAhbIgeAAIgBAUIgCATIgEAUQgCAKgDAHQgEAHgEAFQgFAEgHAAg");
	this.shape_4.setTransform(99,-4.4);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgUA0QgJgEgFgHQgGgIgDgKQgDgKAAgNQAAgNADgKQADgKAGgHQAMgPAWAAQAMAAAJAEQAJAEAGAHQAFAIADAKQADAKAAAMQAAANgDALQgDAKgGAHQgMAPgXAAQgLAAgJgEgAgcAAQAAAIACAHQABAIAEAGQADAFAGAEQAFADAHAAQAPAAAHgKQAHgKAAgVQAAgIgBgHQgCgHgDgGQgEgFgFgEQgGgDgIAAQgcAAAAAog");
	this.shape_5.setTransform(88.7,-4.5);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgiA/QgMgRAAgjQAAgRACgNQACgNADgJQAEgJAFgFQAFgGAGgDQAHgDAHgBIAPgCIASgDQAGgBAEgEIACAQIgFADIgGACIgJABIgMABIgPADQgHABgFAFQgFAFgDAIQgDAIgBAOIABAAQAHgKAJgEQAIgEAMAAQAUAAAKANQALAMAAAYQAAAdgMAPQgNAPgWAAQgWAAgMgQgAgKgMQgGACgEAFQgIAJAAATQAAAIACAIQABAHAEAGQADAFAGAEQAGADAGAAQAIAAAFgDQAFgCAEgGQAHgKAAgVQAAgIgBgHQgCgHgDgEQgDgFgFgDQgFgCgHAAQgHAAgGACg");
	this.shape_6.setTransform(77.3,-6.8);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AAYBLIAAg/IACgNIgCAAIgIANIgvA/IgKAAIAAhqIARAAIAABAIAAANIAAAAIAJgOIAug/IALAAIAABqgAgJguQgFgBgFgDQgEgDgDgFQgEgFgBgGIAPgFQACAJAFAFQAFADAGAAQAHAAAFgDQAFgFACgJIAOAEQgDANgJAGQgJAHgMAAIgLgCg");
	this.shape_7.setTransform(60.1,-6.6);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgWA1QgFgCgFgEQgEgEgCgFQgDgGAAgHQAAgKAEgGQAEgGAHgDQAHgEAJgBQAKgCALAAIAGAAIAGABIAAgMIgBgKIgDgGQgDgDgEgBIgKgBIgHAAIgJACIgIADIgHADIgGgOQAJgFAKgCQALgCALAAQALAAAHADQAHADADAFQAEAFABAFIABAMIgBAYIAAAXIAAAPIADANIgNAAIgEgPIgBAAIgFAGIgHAFIgKADQgEACgHAAQgHAAgGgCgAgBAGQgHABgFABQgEADgDADQgDAEAAAFQAAAHAFAFQAGAFAIAAQAFAAAFgBIAIgFIAFgFIAEgGIAAgSIgGAAIgGAAg");
	this.shape_8.setTransform(48.6,-4.5);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AAYA1IAAgvIgvAAIAAAvIgRAAIAAhpIARAAIAAAtIAvAAIAAgtIARAAIAABpg");
	this.shape_9.setTransform(37.9,-4.5);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgYA1IgNgEIAFgPQAFADAHACQAHABAIAAQAMAAAHgEQAGgFAAgJQABgIgHgEIgIgDIgMgBIgMAAIAAgNIAOAAIAHgCIAHgDIAFgFIACgHQAAgIgGgEQgGgDgLAAQgIAAgHACIgLAFIgEgNQAGgEAIgCQAKgDAMAAQAQAAAJAGQAJAHAAANQAAAIgFAHQgFAHgJADIAAABQANACAFAGQACADACAEQABAFAAAFQAAAHgDAGQgDAGgFAEQgGAEgJADQgIACgKAAQgLAAgHgCg");
	this.shape_10.setTransform(27.3,-4.5);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgfBKIgIgDIAGgPQAEACADABIAHABQAGAAAEgHQAEgFADgNIg3htIAUAAIAmBOIAFATIABAAIAEgUIAdhNIASAAIgmBgIgKAZQgEAKgFAHQgDAGgFADQgFADgIAAIgLgCg");
	this.shape_11.setTransform(16.9,-6.6);

	this.instance = new lib.Symbol16();
	this.instance.parent = this;
	this.instance.setTransform(79.8,-5.3,0.877,0.458,0,0,0,93.9,38.3);
	this.instance.alpha = 0.781;

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol13, new cjs.Rectangle(-2.6,-22.8,165,35.3), null);


(lib.Symbol9 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_255 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(255).call(this.frame_255).wait(39));

	// Symbol 8
	this.instance = new lib.Symbol8();
	this.instance.parent = this;
	this.instance.setTransform(258.5,201.5,0.949,1,0,0,0,246,201.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({scaleX:1,x:66,y:199.5},255).wait(39));

	// Symbol 6
	this.instance_1 = new lib.Symbol6();
	this.instance_1.parent = this;
	this.instance_1.setTransform(130.5,89.5,1.13,1.13,0,0,0,126.5,95.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({scaleX:1,scaleY:1,x:-14.5,y:90.5},255).wait(39));

	// Symbol 7
	this.instance_2 = new lib.Symbol7();
	this.instance_2.parent = this;
	this.instance_2.setTransform(287.5,95.5,1,1,0,0,0,146.5,95.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).to({x:198.5},255).wait(39));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-22.5,-28.2,517.4,431.3);


(lib.Symbol5 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// 2front.jpg
	this.instance = new lib.Symbol11();
	this.instance.parent = this;
	this.instance.setTransform(40,314.5,1,1,0,0,0,230,83.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({x:237},154).wait(79));

	// 3middle.jpg
	this.instance_1 = new lib.Symbol10();
	this.instance_1.parent = this;
	this.instance_1.setTransform(26,145.5,1,1,0,0,0,230,146.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({x:176},154).wait(79));

	// 3tree.jpg
	this.instance_2 = new lib.Symbol12();
	this.instance_2.parent = this;
	this.instance_2.setTransform(47,73,1,1,0,0,0,180,75);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).to({x:147},154).wait(79));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-204,-5.5,514,417.9);


(lib.Symbol1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Symbol 4
	this.instance = new lib.Symbol4();
	this.instance.parent = this;
	this.instance.setTransform(355.6,583.5,0.958,1,0,0,0,229,100.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({scaleX:1,x:184},176).wait(29));

	// Symbol 3
	this.instance_1 = new lib.Symbol3();
	this.instance_1.parent = this;
	this.instance_1.setTransform(458,484.5,1,1,0,0,0,77,136.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({regX:77.2,regY:136.6,scaleX:1.58,x:321.3,y:484.6},176).wait(29));

	// Symbol 2
	this.instance_2 = new lib.Symbol2();
	this.instance_2.parent = this;
	this.instance_2.setTransform(222.7,481.1,1.121,1,0,0,0,164.7,133.1);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).to({regX:164.5,regY:133,scaleX:0.71,x:124,y:481},176).wait(29));

	// 2-grass1.jpg
	this.instance_3 = new lib.Tween1("synched",0);
	this.instance_3.parent = this;
	this.instance_3.setTransform(328,681.5);

	this.instance_4 = new lib.Tween2("synched",0);
	this.instance_4.parent = this;
	this.instance_4.setTransform(151,681.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_3}]}).to({state:[{t:this.instance_4}]},176).wait(29));
	this.timeline.addTween(cjs.Tween.get(this.instance_3).to({_off:true,x:151},176).wait(29));

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#294D27").s().p("EgfAAkaMAAAhIzMA+BAAAMAAABIzg");
	this.shape.setTransform(282,534.4);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(205));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(36.9,301.5,540.2,466);


(lib.main = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 16
	this.instance = new lib.Symbol13();
	this.instance.parent = this;
	this.instance.setTransform(175.5,392.9,0.83,0.83,0,0,0,79.5,16.1);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(445));

	// Layer 10
	this.instance_1 = new lib.Symbol15();
	this.instance_1.parent = this;
	this.instance_1.setTransform(175.2,406.8,1,1,0,0,0,119.6,14);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(346).to({_off:false},0).to({alpha:1},14).wait(73).to({alpha:0},11).wait(1));

	// Layer 9
	this.instance_2 = new lib.t3();
	this.instance_2.parent = this;
	this.instance_2.setTransform(175.5,330.4,1,1,0,0,0,83.9,28.4);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(228).to({_off:false},0).to({alpha:1},18).wait(185).to({alpha:0},12).to({_off:true},1).wait(1));

	// Layer 8
	this.instance_3 = new lib.t2();
	this.instance_3.parent = this;
	this.instance_3.setTransform(175.5,330.4,1,1,0,0,0,83.9,28.4);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(133).to({_off:false},0).to({alpha:1},18).wait(74).to({alpha:0},12).to({_off:true},1).wait(207));

	// Layer 7
	this.instance_4 = new lib.t1();
	this.instance_4.parent = this;
	this.instance_4.setTransform(175.5,330.4,1,1,0,0,0,83.9,28.4);
	this.instance_4.alpha = 0;
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(40).to({_off:false},0).to({alpha:1},18).wait(74).to({alpha:0},12).to({_off:true},1).wait(300));

	// Layer 6
	this.instance_5 = new lib.tree1();
	this.instance_5.parent = this;
	this.instance_5.setTransform(173.3,164.6,0.3,0.3,0,0,0,116.2,116);

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(445));

	// Layer 5
	this.instance_6 = new lib.blackup1();
	this.instance_6.parent = this;
	this.instance_6.setTransform(174.5,27.5,1,1,0,0,0,143,217);

	this.timeline.addTween(cjs.Tween.get(this.instance_6).to({y:305.5,alpha:0.539},93).wait(352));

	// Layer 2
	this.instance_7 = new lib.Symbol1();
	this.instance_7.parent = this;
	this.instance_7.setTransform(173.5,-80,1,1,0,0,0,256.5,246);
	this.instance_7.alpha = 0;
	this.instance_7._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(132).to({_off:false},0).to({alpha:1},15).wait(141).to({alpha:0},15).to({_off:true},1).wait(141));

	// Layer 3
	this.instance_8 = new lib.Symbol5();
	this.instance_8.parent = this;
	this.instance_8.setTransform(279,224,1,1,0,0,0,230,201);
	this.instance_8._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(288).to({_off:false},0).wait(157));

	// Layer 1
	this.instance_9 = new lib.Symbol9();
	this.instance_9.parent = this;
	this.instance_9.setTransform(258.5,219.9,1,1,0,0,0,246,201.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_9).to({_off:true},147).wait(298));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-10.1,-189.5,517.4,617);


// stage content:
(lib.zhk_yandex_240x400_rev001 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 4
	this.instance = new lib.border();
	this.instance.parent = this;
	this.instance.setTransform(120,200,1,1,0,0,0,119.5,199.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// Layer 3
	this.instance_1 = new lib.main();
	this.instance_1.parent = this;
	this.instance_1.setTransform(193.2,185.4,1,1,0,0,0,248.6,205.8);

	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AylfLMAAAg+VMAlLAAAMAAAA+Vg");
	this.shape.setTransform(119,199.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape},{t:this.instance_1}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(54.5,-9.9,517.4,617);
// library properties:
lib.properties = {
	id: '943EBE109F574202AF204F6D32F81FF5',
	width: 240,
	height: 400,
	fps: 30,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/_1rearbg.jpg?1499785139666", id:"_1rearbg"},
		{src:"images/_1front.jpg?1499785139666", id:"_1front"},
		{src:"images/_1left.jpg?1499785139666", id:"_1left"},
		{src:"images/_2grass1.jpg?1499785139666", id:"_2grass1"},
		{src:"images/_2upleft.jpg?1499785139666", id:"_2upleft"},
		{src:"images/_2front.jpg?1499785139666", id:"_2front"},
		{src:"images/_3grass2.jpg?1499785139666", id:"_3grass2"},
		{src:"images/_3middle.jpg?1499785139666", id:"_3middle"},
		{src:"images/_3rear2.jpg?1499785139666", id:"_3rear2"},
		{src:"images/_3right.jpg?1499785139666", id:"_3right"},
		{src:"images/Bitmap1.png?1499785139666", id:"Bitmap1"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['943EBE109F574202AF204F6D32F81FF5'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}



})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;